// Script to seed 30 top trending tourist destinations in India
const { MongoClient } = require("mongodb");
require("dotenv").config();
const { enrichDestination } = require("./utils/enrichDestination");

const MONGODB_URI = process.env.MONGODB_URI || "mongodb://127.0.0.1:27017";
const DB_NAME = "tourease";

const top30TrendingDestinations = [
  {
    name: "Taj Mahal",
    category: "Historical",
    description:
      "The Taj Mahal is an ivory-white marble mausoleum, built by Mughal emperor Shah Jahan in memory of his wife Mumtaz Mahal. One of the Seven Wonders of the World and UNESCO World Heritage Site, it stands as a timeless symbol of love and architectural brilliance.",
    location: {
      city: "Agra",
      state: "Uttar Pradesh",
      country: "India",
      coordinates: { lat: 27.1751, lng: 78.0421 },
      address: "Dharmapuri, Forest Colony, Tajganj, Agra, Uttar Pradesh 282001",
    },
    rating: 4.9,
    reviews: 125000,
    entryFee: "₹50 Indians, ₹1300 Foreigners",
    timings: "Sunrise to Sunset (Closed Fridays)",
    bestTimeToVisit: "October to March",
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800",
    highlights: [
      "UNESCO World Heritage Site",
      "Seven Wonders of the World",
      "White marble architecture",
      "Mughal Gardens",
      "Intricate inlay work",
    ],
    activities: ["Photography", "Heritage tours", "Sunrise viewing", "Garden walks"],
    nearbyAttractions: [
      { name: "Agra Fort", distance: "2.5 km" },
      { name: "Fatehpur Sikri", distance: "40 km" },
    ],
    howToReach: "Agra Airport 13 km, Delhi Airport 230 km, Agra Cantt Station 6 km",
    tips: ["Book tickets online", "Visit on weekdays", "No food/tobacco inside", "Carry valid ID"],
    contactNumber: "+91-562-2227261",
    website: "https://www.tajmahal.gov.in",
    trending: true,
    trendingRank: 1,
    popularity: 100,
  },

  {
    name: "Jaipur - The Pink City",
    category: "Historical",
    description:
      "Jaipur, the capital of Rajasthan, is known as the Pink City due to its distinctively colored buildings. Famous for stunning palaces, forts, vibrant bazaars, and rich Rajasthani culture.",
    location: {
      city: "Jaipur",
      state: "Rajasthan",
      country: "India",
      coordinates: { lat: 26.9124, lng: 75.7873 },
      address: "Jaipur, Rajasthan, India",
    },
    rating: 4.7,
    reviews: 98000,
    entryFee: "₹200-500 per monument",
    timings: "9:00 AM - 5:00 PM",
    bestTimeToVisit: "October to March",
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800",
    highlights: [
      "Amber Fort",
      "Hawa Mahal",
      "City Palace",
      "Jantar Mantar UNESCO Site",
      "Jal Mahal",
      "Nahargarh Fort",
    ],
    activities: [
      "Elephant ride at Amber",
      "Hot air balloon ride",
      "Shopping for jewelry",
      "Traditional dinner with cultural show",
    ],
    nearbyAttractions: [
      { name: "Pushkar", distance: "145 km" },
      { name: "Ranthambore", distance: "180 km" },
    ],
    howToReach: "Jaipur Int'l Airport, Jaipur Railway Station, NH 8 from Delhi 280 km",
    tips: ["Bargain at markets", "Visit Sunday for palace illumination", "Hire audio guide"],
    contactNumber: "+91-141-2221111",
    website: "https://tourism.rajasthan.gov.in",
    trending: true,
    trendingRank: 2,
    popularity: 95,
  },

  {
    name: "Goa Beaches",
    category: "Beach",
    description:
      "Goa, India's smallest state, is renowned for pristine beaches, vibrant nightlife, Portuguese heritage, and laid-back atmosphere. Perfect blend of Indian and Portuguese cultures.",
    location: {
      city: "Goa",
      state: "Goa",
      country: "India",
      coordinates: { lat: 15.2993, lng: 74.124 },
      address: "Goa, India",
    },
    rating: 4.8,
    reviews: 156000,
    entryFee: "Beaches free, Water sports ₹500-3000",
    timings: "24/7 (Beaches), Clubs 9 PM - 4 AM",
    bestTimeToVisit: "November to February",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800",
    highlights: [
      "Baga Beach nightlife",
      "Calangute Beach",
      "Palolem Beach",
      "Basilica of Bom Jesus",
      "Fort Aguada",
      "Dudhsagar Falls",
    ],
    activities: [
      "Parasailing",
      "Scuba diving",
      "Dolphin watching",
      "Beach parties",
      "Casino cruises",
      "Spice plantation tours",
    ],
    nearbyAttractions: [
      { name: "Dudhsagar Falls", distance: "60 km" },
      { name: "Old Goa Churches", distance: "10 km" },
    ],
    howToReach: "Goa Airport Dabolim 30 km, Madgaon Station, NH 66 from Mumbai 580 km",
    tips: [
      "Rent scooter for mobility",
      "Book Dec-Jan in advance",
      "Respect beach rules",
      "Try authentic Goan food",
    ],
    contactNumber: "+91-832-2438750",
    website: "https://www.goatourism.gov.in",
    trending: true,
    trendingRank: 3,
    popularity: 98,
  },

  {
    name: "Varanasi (Kashi)",
    category: "Religious",
    description:
      "Varanasi, one of the oldest cities in the world (3000+ years), is the spiritual capital of India. Famous for ghats, temples, Ganga Aarti, and as a center of learning and culture.",
    location: {
      city: "Varanasi",
      state: "Uttar Pradesh",
      country: "India",
      coordinates: { lat: 25.3176, lng: 82.9739 },
      address: "Varanasi, Uttar Pradesh, India",
    },
    rating: 4.7,
    reviews: 87000,
    entryFee: "Ghats free, Boat ride ₹150-300",
    timings: "24/7 (Ghats)",
    bestTimeToVisit: "October to March",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800",
    highlights: [
      "Dashashwamedh Ghat Aarti",
      "Kashi Vishwanath Temple",
      "Assi Ghat",
      "Sarnath",
      "BHU",
      "Ramnagar Fort",
    ],
    activities: [
      "Sunrise boat ride",
      "Evening Ganga Aarti",
      "Heritage walks",
      "Silk shopping",
      "Classical music concerts",
    ],
    nearbyAttractions: [
      { name: "Sarnath", distance: "10 km" },
      { name: "Chunar Fort", distance: "40 km" },
    ],
    howToReach: "Lal Bahadur Shastri Airport 25 km, Varanasi Junction Station",
    tips: [
      "Dress modestly",
      "Bargain for boat rides",
      "Respect cremation ceremonies",
      "Carry cash",
    ],
    contactNumber: "+91-542-2506670",
    website: "https://www.varanasi.nic.in",
    trending: true,
    trendingRank: 4,
    popularity: 92,
  },

  {
    name: "Kerala Backwaters",
    category: "Natural Wonder",
    description:
      "A network of 900+ km of interconnected canals, rivers, lakes, and inlets along Kerala's coast. Famous for houseboats, lush greenery, and serene village life.",
    location: {
      city: "Alleppey (Alappuzha)",
      state: "Kerala",
      country: "India",
      coordinates: { lat: 9.4981, lng: 76.3388 },
      address: "Alleppey, Kerala, India",
    },
    rating: 4.8,
    reviews: 94000,
    entryFee: "Houseboat ₹8,000-25,000",
    timings: "Check-in 12 PM, Check-out 9 AM",
    bestTimeToVisit: "November to February",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800",
    highlights: [
      "Houseboat stays",
      "Vembanad Lake",
      "Kumarakom Bird Sanctuary",
      "Nehru Trophy Boat Race",
      "Traditional villages",
    ],
    activities: [
      "Houseboat cruise",
      "Canoeing",
      "Village walks",
      "Ayurvedic treatments",
      "Bird watching",
      "Fishing",
    ],
    nearbyAttractions: [
      { name: "Munnar", distance: "160 km" },
      { name: "Cochin", distance: "85 km" },
    ],
    howToReach: "Cochin Airport 85 km, Alleppey Station, NH 66",
    tips: [
      "Book houseboats in advance",
      "Carry mosquito repellent",
      "Try Karimeen fish",
      "Respect village customs",
    ],
    contactNumber: "+91-477-2253308",
    website: "https://www.keralatourism.org",
    trending: true,
    trendingRank: 5,
    popularity: 93,
  },

  {
    name: "Ladakh - Land of High Passes",
    category: "Adventure",
    description:
      "High-altitude desert with stunning landscapes, Buddhist monasteries, adventurous roads, and pristine lakes. Features world's highest motorable passes and unique Tibetan Buddhist culture.",
    location: {
      city: "Leh",
      state: "Ladakh",
      country: "India",
      coordinates: { lat: 34.1526, lng: 77.5771 },
      address: "Leh, Ladakh, India",
    },
    rating: 4.9,
    reviews: 112000,
    entryFee: "Permits ₹400-800, Monasteries ₹50-100",
    timings: "Weather dependent",
    bestTimeToVisit: "May to September",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    highlights: [
      "Pangong Lake",
      "Nubra Valley",
      "Khardung La Pass",
      "Magnetic Hill",
      "Thiksey Monastery",
      "Hemis Monastery",
      "Shanti Stupa",
    ],
    activities: [
      "Motorcycle tours",
      "River rafting",
      "Trekking",
      "Camping",
      "Stargazing",
      "Monastery visits",
    ],
    nearbyAttractions: [
      { name: "Pangong Lake", distance: "160 km" },
      { name: "Nubra Valley", distance: "120 km" },
    ],
    howToReach: "Leh Airport (best), Manali-Leh Highway 475 km, Srinagar-Leh 420 km",
    tips: [
      "Acclimatize 2-3 days",
      "Get Inner Line Permits",
      "Carry AMS medicines",
      "Pack warm clothes",
      "Carry cash",
    ],
    contactNumber: "+91-1982-252297",
    website: "https://www.ladakh.nic.in",
    trending: true,
    trendingRank: 6,
    popularity: 96,
  },

  {
    name: "Rishikesh - Yoga Capital",
    category: "Adventure",
    description:
      "Spiritual town in Himalayan foothills on Ganges River, known as Yoga Capital of the World. Famous for temples, ashrams, adventure sports, and Beatles Ashram.",
    location: {
      city: "Rishikesh",
      state: "Uttarakhand",
      country: "India",
      coordinates: { lat: 30.0869, lng: 78.2676 },
      address: "Rishikesh, Uttarakhand, India",
    },
    rating: 4.7,
    reviews: 78000,
    entryFee: "Temples free, Rafting ₹500-2500, Bungee ₹3500",
    timings: "Temples 5 AM - 9 PM",
    bestTimeToVisit: "September to November, March to May",
    image: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800",
    highlights: [
      "Lakshman Jhula",
      "Ram Jhula",
      "Triveni Ghat Aarti",
      "Beatles Ashram",
      "Parmarth Niketan",
      "Adventure sports",
    ],
    activities: [
      "White water rafting",
      "Bungee jumping",
      "Yoga retreats",
      "River camping",
      "Trekking",
      "Cafe hopping",
    ],
    nearbyAttractions: [
      { name: "Haridwar", distance: "20 km" },
      { name: "Mussoorie", distance: "75 km" },
    ],
    howToReach: "Jolly Grant Airport Dehradun 35 km, Haridwar Station 25 km, Delhi 240 km",
    tips: [
      "Alcohol/meat free zone",
      "Book rafting from certified operators",
      "Wear modest clothes",
      "Carry ID for activities",
    ],
    contactNumber: "+91-135-2430209",
    website: "https://uttarakhandtourism.gov.in",
    trending: true,
    trendingRank: 7,
    popularity: 89,
  },

  {
    name: "Darjeeling - Queen of Hills",
    category: "Hill Station",
    description:
      "Picturesque hill station famous for tea plantations, Kanchenjunga views, colonial architecture, and UNESCO Heritage Toy Train. Blend of Nepali, Tibetan, and British cultures.",
    location: {
      city: "Darjeeling",
      state: "West Bengal",
      country: "India",
      coordinates: { lat: 27.041, lng: 88.2663 },
      address: "Darjeeling, West Bengal, India",
    },
    rating: 4.6,
    reviews: 72000,
    entryFee: "Toy Train ₹1,390 Joy Ride, Zoo ₹50",
    timings: "Sunrise point 4 AM, Attractions 8 AM - 5 PM",
    bestTimeToVisit: "March to May, October to December",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800",
    highlights: [
      "Tiger Hill sunrise",
      "Toy Train",
      "Tea gardens",
      "Batasia Loop",
      "Peace Pagoda",
      "Himalayan Zoo",
      "Happy Valley Estate",
    ],
    activities: [
      "Toy train ride",
      "Tea tasting",
      "Sunrise viewing",
      "Cable car ride",
      "Monastery visits",
      "Shopping",
    ],
    nearbyAttractions: [
      { name: "Kalimpong", distance: "50 km" },
      { name: "Gangtok", distance: "98 km" },
    ],
    howToReach: "Bagdogra Airport 95 km, New Jalpaiguri Station 70 km, Siliguri 70 km",
    tips: [
      "Book toy train advance",
      "Tiger Hill needs 3:30 AM start",
      "Carry warm clothes",
      "Try fresh Darjeeling tea",
    ],
    contactNumber: "+91-354-2254102",
    website: "https://darjeelingtourism.gov.in",
    trending: true,
    trendingRank: 8,
    popularity: 87,
  },

  {
    name: "Andaman Islands",
    category: "Beach",
    description:
      "Tropical islands with pristine beaches, turquoise waters, coral reefs, and rich marine life. Famous for water sports, scuba diving, and historical Cellular Jail.",
    location: {
      city: "Port Blair",
      state: "Andaman and Nicobar Islands",
      country: "India",
      coordinates: { lat: 11.6234, lng: 92.7265 },
      address: "Port Blair, Andaman, India",
    },
    rating: 4.8,
    reviews: 85000,
    entryFee: "Beaches free, Scuba ₹3,500-5,500",
    timings: "Beaches open all day",
    bestTimeToVisit: "October to May",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    highlights: [
      "Radhanagar Beach",
      "Cellular Jail",
      "Ross Island",
      "Neil Island",
      "Elephant Beach",
      "North Bay",
      "Baratang Caves",
    ],
    activities: [
      "Scuba diving",
      "Snorkeling",
      "Sea walking",
      "Parasailing",
      "Island hopping",
      "Glass bottom boat",
      "Beach camping",
    ],
    nearbyAttractions: [
      { name: "Havelock Island", distance: "54 km by sea" },
      { name: "Neil Island", distance: "37 km by sea" },
    ],
    howToReach: "Port Blair Airport, Ships from Kolkata/Chennai (3-4 days)",
    tips: [
      "Book ferries advance",
      "Carry cash",
      "Use reef-safe sunscreen",
      "Get RAP for foreigners",
    ],
    contactNumber: "+91-3192-233006",
    website: "https://www.andamans.gov.in",
    trending: true,
    trendingRank: 9,
    popularity: 91,
  },

  {
    name: "Mysore Palace",
    category: "Historical",
    description:
      "Magnificent Indo-Saracenic palace, one of India's most visited monuments. Features grand arches, ornate halls, and illuminated with 100,000 bulbs on Sundays.",
    location: {
      city: "Mysore",
      state: "Karnataka",
      country: "India",
      coordinates: { lat: 12.3052, lng: 76.6551 },
      address: "Sayyaji Rao Road, Mysuru, Karnataka 570001",
    },
    rating: 4.7,
    reviews: 95000,
    entryFee: "₹70 Indians, ₹200 Foreigners",
    timings: "10 AM - 5:30 PM, Illumination Sundays 7-8 PM",
    bestTimeToVisit: "October to February, Dasara Festival",
    image: "https://images.unsplash.com/photo-1609416917477-fde942239fbf?w=800",
    highlights: [
      "Indo-Saracenic architecture",
      "Durbar Hall",
      "Golden Howdah",
      "Sunday illumination",
      "Dasara celebrations",
      "Royal museum",
    ],
    activities: [
      "Guided tours",
      "Dasara procession",
      "Photography (exterior)",
      "Palace grounds walks",
    ],
    nearbyAttractions: [
      { name: "Chamundi Hills", distance: "13 km" },
      { name: "Brindavan Gardens", distance: "21 km" },
    ],
    howToReach: "Mysore Airport 10 km, Bangalore Airport 170 km, Mysore Station 2 km",
    tips: [
      "No photography inside",
      "Remove footwear",
      "Visit Sunday evening for lights",
      "Attend Dasara festival",
    ],
    contactNumber: "+91-821-2421051",
    website: "https://mysorepalace.gov.in",
    trending: true,
    trendingRank: 10,
    popularity: 88,
  },

  {
    name: "Hampi",
    category: "Historical",
    description:
      "UNESCO World Heritage Site with ruins of Vijayanagara Empire. Ancient temples, massive boulders, and stunning landscapes create a surreal archaeological wonder.",
    location: {
      city: "Hampi",
      state: "Karnataka",
      country: "India",
      coordinates: { lat: 15.335, lng: 76.46 },
      address: "Hampi, Karnataka, India",
    },
    rating: 4.7,
    reviews: 68000,
    entryFee: "₹40 Indians, ₹600 Foreigners",
    timings: "6 AM - 6 PM",
    bestTimeToVisit: "October to February",
    image: "https://images.unsplash.com/photo-1588416936097-41850ab3d86d?w=800",
    highlights: [
      "Virupaksha Temple",
      "Stone Chariot",
      "Vittala Temple",
      "Elephant Stables",
      "Lotus Mahal",
      "Matanga Hill sunrise",
    ],
    activities: [
      "Temple exploration",
      "Rock climbing",
      "Coracle rides",
      "Cycling tours",
      "Sunrise/sunset viewing",
    ],
    nearbyAttractions: [
      { name: "Badami Caves", distance: "140 km" },
      { name: "Pattadakal", distance: "135 km" },
    ],
    howToReach: "Hubli Airport 160 km, Hospet Station 13 km, Bangalore 350 km",
    tips: [
      "Rent bicycle/scooter",
      "Wear comfortable shoes",
      "Carry water",
      "Climb Matanga Hill for sunset",
    ],
    contactNumber: "+91-8394-241339",
    website: "https://karnatakatourism.org",
    trending: true,
    trendingRank: 11,
    popularity: 85,
  },

  {
    name: "Udaipur - City of Lakes",
    category: "Historical",
    description:
      "Romantic city with beautiful palaces, lakes, and havelis. Known as Venice of the East, famous for City Palace, Lake Pichola, and Rajasthani culture.",
    location: {
      city: "Udaipur",
      state: "Rajasthan",
      country: "India",
      coordinates: { lat: 24.5854, lng: 73.7125 },
      address: "Udaipur, Rajasthan, India",
    },
    rating: 4.7,
    reviews: 82000,
    entryFee: "₹300 City Palace, ₹700 Lake Palace view",
    timings: "9:30 AM - 5:30 PM",
    bestTimeToVisit: "September to March",
    image: "https://images.unsplash.com/photo-1580055733199-07e48814c6dc?w=800",
    highlights: [
      "City Palace",
      "Lake Pichola",
      "Jag Mandir",
      "Jag Niwas (Lake Palace Hotel)",
      "Saheliyon Ki Bari",
      "Bagore Ki Haveli",
    ],
    activities: [
      "Boat rides",
      "Palace tours",
      "Cultural shows",
      "Shopping",
      "Rooftop dining",
      "Heritage walks",
    ],
    nearbyAttractions: [
      { name: "Kumbhalgarh Fort", distance: "85 km" },
      { name: "Chittorgarh", distance: "115 km" },
    ],
    howToReach: "Maharana Pratap Airport 22 km, Udaipur City Station, NH 8",
    tips: [
      "Book lake view hotels",
      "Take sunset boat ride",
      "Attend cultural show at Bagore Ki Haveli",
      "Walk old city lanes",
    ],
    contactNumber: "+91-294-2411535",
    website: "https://tourism.rajasthan.gov.in",
    trending: true,
    trendingRank: 12,
    popularity: 86,
  },

  {
    name: "Munnar",
    category: "Hill Station",
    description:
      "Picturesque hill station in Western Ghats, famous for tea plantations, misty mountains, and pleasant climate. Ideal for nature lovers and honeymooners.",
    location: {
      city: "Munnar",
      state: "Kerala",
      country: "India",
      coordinates: { lat: 10.0889, lng: 77.0595 },
      address: "Munnar, Kerala, India",
    },
    rating: 4.6,
    reviews: 71000,
    entryFee: "Tea museum ₹125, National Park ₹360",
    timings: "Tea estates 8 AM - 5 PM",
    bestTimeToVisit: "September to March",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800",
    highlights: [
      "Tea plantations",
      "Anamudi Peak",
      "Mattupetty Dam",
      "Echo Point",
      "Eravikulam National Park",
      "Tea Museum",
    ],
    activities: [
      "Tea estate tours",
      "Trekking",
      "Boating",
      "Wildlife spotting",
      "Photography",
      "Cycling",
    ],
    nearbyAttractions: [
      { name: "Thekkady", distance: "90 km" },
      { name: "Alleppey", distance: "160 km" },
    ],
    howToReach: "Cochin Airport 110 km, Aluva Station 110 km, Madurai 140 km",
    tips: [
      "Carry warm clothes",
      "Try fresh tea",
      "Book Neelakurinji season (once in 12 years)",
      "Hire local taxi",
    ],
    contactNumber: "+91-4865-231516",
    website: "https://www.keralatourism.org",
    trending: true,
    trendingRank: 13,
    popularity: 84,
  },

  {
    name: "Coorg",
    category: "Hill Station",
    description:
      "Scotland of India, known for coffee plantations, lush green hills, waterfalls, and Kodava culture. Perfect for nature walks and plantation stays.",
    location: {
      city: "Coorg (Kodagu)",
      state: "Karnataka",
      country: "India",
      coordinates: { lat: 12.3375, lng: 75.8069 },
      address: "Coorg, Karnataka, India",
    },
    rating: 4.6,
    reviews: 65000,
    entryFee: "Abbey Falls ₹15, Dubare Camp ₹300",
    timings: "Daylight hours for outdoor activities",
    bestTimeToVisit: "October to March",
    image: "https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=800",
    highlights: [
      "Coffee plantations",
      "Abbey Falls",
      "Raja's Seat",
      "Dubare Elephant Camp",
      "Talakaveri",
      "Nagarhole National Park",
    ],
    activities: [
      "Plantation tours",
      "Trekking",
      "River rafting",
      "Elephant interaction",
      "Bird watching",
      "Coffee tasting",
    ],
    nearbyAttractions: [
      { name: "Mysore", distance: "120 km" },
      { name: "Nagarhole", distance: "60 km" },
    ],
    howToReach: "Mangalore Airport 160 km, Mysore Station 120 km, Bangalore 260 km",
    tips: [
      "Stay in homestays",
      "Try Pandi Curry",
      "Buy fresh coffee",
      "Monsoon offers lush beauty",
    ],
    contactNumber: "+91-8272-228580",
    website: "https://karnatakatourism.org",
    trending: true,
    trendingRank: 14,
    popularity: 83,
  },

  {
    name: "Shimla",
    category: "Hill Station",
    description:
      "Former summer capital of British India, famous for colonial architecture, Mall Road, toy train, and pleasant climate. Popular honeymoon destination.",
    location: {
      city: "Shimla",
      state: "Himachal Pradesh",
      country: "India",
      coordinates: { lat: 31.1048, lng: 77.1734 },
      address: "Shimla, Himachal Pradesh, India",
    },
    rating: 4.5,
    reviews: 79000,
    entryFee: "Most attractions free, Museum ₹50",
    timings: "Mall Road all day, Museums 10 AM - 5 PM",
    bestTimeToVisit: "March to June (Summer), December to February (Snow)",
    image: "https://images.unsplash.com/photo-1566837945700-30057527ade0?w=800",
    highlights: [
      "Mall Road",
      "The Ridge",
      "Christ Church",
      "Viceregal Lodge",
      "Jakhoo Temple",
      "Toy Train",
      "Kufri",
    ],
    activities: [
      "Shopping on Mall Road",
      "Toy train ride",
      "Trekking",
      "Ice skating (winter)",
      "Horse riding",
      "Photography",
    ],
    nearbyAttractions: [
      { name: "Kufri", distance: "16 km" },
      { name: "Manali", distance: "250 km" },
    ],
    howToReach: "Chandigarh Airport 115 km, Kalka Station (toy train), NH 5 from Chandigarh",
    tips: [
      "Book hotels advance in season",
      "Toy train Kalka-Shimla is scenic",
      "Carry woolens",
      "Walk Mall Road",
    ],
    contactNumber: "+91-177-2652561",
    website: "https://himachaltourism.gov.in",
    trending: true,
    trendingRank: 15,
    popularity: 82,
  },

  {
    name: "Manali",
    category: "Hill Station",
    description:
      "Popular hill station at the northern end of Kullu Valley, gateway to Rohtang Pass and Lahaul-Spiti. Famous for adventure sports, scenic beauty, and backpacker culture.",
    location: {
      city: "Manali",
      state: "Himachal Pradesh",
      country: "India",
      coordinates: { lat: 32.2432, lng: 77.1892 },
      address: "Manali, Himachal Pradesh, India",
    },
    rating: 4.6,
    reviews: 91000,
    entryFee: "Rohtang Pass permit ₹500, Activities vary",
    timings: "Open all day, Rohtang 7 AM - 4 PM (May-Oct)",
    bestTimeToVisit: "October to February (Snow), May to June (Summer)",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800",
    highlights: [
      "Rohtang Pass",
      "Solang Valley",
      "Hadimba Temple",
      "Old Manali",
      "Vashisht Hot Springs",
      "Manu Temple",
      "Beas River",
    ],
    activities: [
      "Skiing",
      "Paragliding",
      "River rafting",
      "Trekking",
      "Cable car",
      "Zorbing",
      "Mountain biking",
    ],
    nearbyAttractions: [
      { name: "Solang Valley", distance: "14 km" },
      { name: "Rohtang Pass", distance: "51 km" },
    ],
    howToReach: "Bhuntar Airport 50 km, Chandigarh 310 km, Delhi 540 km by road",
    tips: [
      "Get Rohtang permit online",
      "Stay in Old Manali for cafes",
      "Carry warm clothes",
      "Try local trout fish",
    ],
    contactNumber: "+91-1902-252116",
    website: "https://himachaltourism.gov.in",
    trending: true,
    trendingRank: 16,
    popularity: 90,
  },

  {
    name: "Amritsar - Golden Temple",
    category: "Religious",
    description:
      "Spiritual center of Sikhism, home to the iconic Golden Temple (Harmandir Sahib). Rich in history, culture, and close to Wagah Border for the Beating Retreat ceremony.",
    location: {
      city: "Amritsar",
      state: "Punjab",
      country: "India",
      coordinates: { lat: 31.634, lng: 74.8723 },
      address: "Amritsar, Punjab, India",
    },
    rating: 4.9,
    reviews: 105000,
    entryFee: "Free (Golden Temple), Wagah ₹0",
    timings: "Golden Temple 24/7, Wagah ceremony 4:15 PM",
    bestTimeToVisit: "November to March",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800",
    highlights: [
      "Golden Temple",
      "Jallianwala Bagh",
      "Wagah Border ceremony",
      "Akal Takht",
      "Durgiana Temple",
      "Partition Museum",
    ],
    activities: [
      "Langar (community meal)",
      "Night viewing of temple",
      "Wagah Border ceremony",
      "Heritage walks",
      "Shopping",
    ],
    nearbyAttractions: [
      { name: "Wagah Border", distance: "30 km" },
      { name: "Pul Kanjari", distance: "35 km" },
    ],
    howToReach: "Amritsar Airport 11 km, Amritsar Junction Station, NH 1 from Delhi 450 km",
    tips: [
      "Cover head at temple",
      "Experience langar",
      "Reach Wagah early for seats",
      "Try Amritsari kulcha",
      "Visit at night for serene view",
    ],
    contactNumber: "+91-183-2401000",
    website: "https://www.goldentempleamritsar.org",
    trending: true,
    trendingRank: 17,
    popularity: 94,
  },

  {
    name: "Khajuraho Temples",
    category: "Historical",
    description:
      "UNESCO World Heritage Site famous for stunning temples with intricate erotic sculptures. Masterpiece of Chandela dynasty showcasing medieval Indian architecture.",
    location: {
      city: "Khajuraho",
      state: "Madhya Pradesh",
      country: "India",
      coordinates: { lat: 24.8318, lng: 79.9199 },
      address: "Khajuraho, Madhya Pradesh, India",
    },
    rating: 4.6,
    reviews: 48000,
    entryFee: "₹40 Indians, ₹600 Foreigners",
    timings: "Sunrise to Sunset, Light Show 7 PM",
    bestTimeToVisit: "October to February",
    image: "https://images.unsplash.com/photo-1609416917477-fde942239fbf?w=800",
    highlights: [
      "Kandariya Mahadev Temple",
      "Lakshmana Temple",
      "Vishwanath Temple",
      "Erotic sculptures",
      "Light and sound show",
    ],
    activities: [
      "Temple exploration",
      "Light show",
      "Archaeological museum visit",
      "Photography",
      "Cultural performances",
    ],
    nearbyAttractions: [
      { name: "Panna National Park", distance: "30 km" },
      { name: "Raneh Falls", distance: "20 km" },
    ],
    howToReach: "Khajuraho Airport well connected, Khajuraho Station, Jhansi 175 km",
    tips: [
      "Hire guide for history",
      "Attend light show",
      "Western group has main temples",
      "Visit early to avoid heat",
    ],
    contactNumber: "+91-7686-272047",
    website: "https://www.mptourism.com",
    trending: true,
    trendingRank: 18,
    popularity: 79,
  },

  {
    name: "Ajanta & Ellora Caves",
    category: "Historical",
    description:
      "UNESCO World Heritage Sites with ancient rock-cut caves. Ajanta has Buddhist frescoes, Ellora features Hindu, Buddhist, and Jain temples carved from rock.",
    location: {
      city: "Aurangabad",
      state: "Maharashtra",
      country: "India",
      coordinates: { lat: 20.5522, lng: 75.7033 },
      address: "Near Aurangabad, Maharashtra, India",
    },
    rating: 4.7,
    reviews: 52000,
    entryFee: "₹40 Indians, ₹600 Foreigners per site",
    timings: "9 AM - 5:30 PM (Closed Mondays for Ajanta, Tuesdays for Ellora)",
    bestTimeToVisit: "October to March",
    image: "https://images.unsplash.com/photo-1609416917477-fde942239fbf?w=800",
    highlights: [
      "Kailasa Temple (Ellora)",
      "Buddhist caves with frescoes (Ajanta)",
      "Rock-cut architecture",
      "Ancient paintings",
      "Multi-faith caves",
    ],
    activities: ["Cave exploration", "Photography", "Historical tours", "Museum visits"],
    nearbyAttractions: [
      { name: "Bibi Ka Maqbara", distance: "30 km from Ellora" },
      { name: "Daulatabad Fort", distance: "15 km" },
    ],
    howToReach: "Aurangabad Airport 30 km, Aurangabad Station, Ajanta 100 km, Ellora 30 km",
    tips: [
      "Visit both caves separate days",
      "Hire guide for history",
      "Carry water",
      "Wear comfortable shoes",
      "Photography restricted in some caves",
    ],
    contactNumber: "+91-240-2331513",
    website: "https://www.maharashtratourism.gov.in",
    trending: true,
    trendingRank: 19,
    popularity: 81,
  },

  {
    name: "Kaziranga National Park",
    category: "Wildlife",
    description:
      "UNESCO World Heritage Site and home to two-thirds of world's one-horned rhinoceroses. Rich biodiversity with elephants, tigers, wild buffalo, and diverse birdlife.",
    location: {
      city: "Kaziranga",
      state: "Assam",
      country: "India",
      coordinates: { lat: 26.5775, lng: 93.1711 },
      address: "Kaziranga, Assam, India",
    },
    rating: 4.7,
    reviews: 38000,
    entryFee: "Indians ₹150, Foreigners ₹1750, Safari ₹1050-2450",
    timings: "Safaris 7 AM & 1:30 PM (Nov-April)",
    bestTimeToVisit: "November to April",
    image: "https://images.unsplash.com/photo-1564760055775-d63b17a55c44?w=800",
    highlights: [
      "One-horned rhinoceros",
      "Bengal tigers",
      "Wild elephants",
      "Swamp deer",
      "Bird watching",
      "Elephant safari",
      "Jeep safari",
    ],
    activities: [
      "Elephant safari",
      "Jeep safari",
      "Bird watching",
      "Nature photography",
      "River cruise",
    ],
    nearbyAttractions: [
      { name: "Majuli Island", distance: "150 km" },
      { name: "Pobitora Wildlife Sanctuary", distance: "48 km" },
    ],
    howToReach: "Jorhat Airport 97 km, Furkating Station 75 km, Guwahati 217 km",
    tips: [
      "Book safari advance",
      "Carry binoculars",
      "Wear muted colors",
      "Park closed July-October (monsoon)",
      "Stay in Kohora",
    ],
    contactNumber: "+91-3776-268095",
    website: "https://www.kaziranga-national-park.com",
    trending: true,
    trendingRank: 20,
    popularity: 77,
  },

  {
    name: "Rann of Kutch",
    category: "Natural Wonder",
    description:
      "Vast white salt desert, spectacular during full moon. Famous for Rann Utsav showcasing Gujarati culture, crafts, and desert camping experience.",
    location: {
      city: "Kutch",
      state: "Gujarat",
      country: "India",
      coordinates: { lat: 23.7337, lng: 69.8597 },
      address: "Rann of Kutch, Gujarat, India",
    },
    rating: 4.6,
    reviews: 42000,
    entryFee: "Tent city packages ₹4000-15000 per night",
    timings: "Best at sunset and full moon nights",
    bestTimeToVisit: "November to February (Rann Utsav)",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800",
    highlights: [
      "White salt desert",
      "Rann Utsav festival",
      "Full moon nights",
      "Desert camping",
      "Handicrafts villages",
      "Kala Dungar viewpoint",
    ],
    activities: [
      "Desert safari",
      "Cultural performances",
      "Handicraft shopping",
      "Camel rides",
      "Paramotoring",
      "Star gazing",
    ],
    nearbyAttractions: [
      { name: "Mandvi Beach", distance: "85 km" },
      { name: "Dholavira", distance: "220 km" },
    ],
    howToReach: "Bhuj Airport 80 km, Bhuj Station 85 km, Ahmedabad 400 km",
    tips: [
      "Visit during Rann Utsav",
      "Book tent city advance",
      "Carry warm clothes for nights",
      "Don't miss full moon",
      "Try local Gujarati food",
    ],
    contactNumber: "+91-2832-241066",
    website: "https://www.gujarattourism.com",
    trending: true,
    trendingRank: 21,
    popularity: 80,
  },

  {
    name: "Valley of Flowers",
    category: "Natural Wonder",
    description:
      "UNESCO World Heritage Site, a high-altitude Himalayan valley famous for endemic alpine flowers and stunning meadows. Trek destination with breathtaking beauty.",
    location: {
      city: "Chamoli",
      state: "Uttarakhand",
      country: "India",
      coordinates: { lat: 30.7268, lng: 79.6009 },
      address: "Chamoli District, Uttarakhand, India",
    },
    rating: 4.8,
    reviews: 32000,
    entryFee: "₹150 Indians, ₹600 Foreigners",
    timings: "June to October (Park open)",
    bestTimeToVisit: "July to September (Peak bloom)",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    highlights: [
      "Alpine flowers meadows",
      "Himalayan trek",
      "Hemkund Sahib nearby",
      "Rare flora fauna",
      "Glacial streams",
      "Mountain views",
    ],
    activities: [
      "Trekking",
      "Photography",
      "Nature walks",
      "Bird watching",
      "Camping at Ghangaria",
    ],
    nearbyAttractions: [
      { name: "Hemkund Sahib", distance: "6 km trek" },
      { name: "Badrinath", distance: "25 km from Govindghat" },
    ],
    howToReach: "Jolly Grant Airport 295 km, Haridwar 273 km, Trek from Govindghat (base)",
    tips: [
      "Moderate fitness required",
      "Trek from Govindghat via Ghangaria",
      "Carry rain gear",
      "Book Ghangaria stay advance",
      "Best in monsoon for flowers",
    ],
    contactNumber: "+91-1372-226137",
    website: "https://uttarakhandtourism.gov.in",
    trending: true,
    trendingRank: 22,
    popularity: 76,
  },

  {
    name: "Sundarbans National Park",
    category: "Wildlife",
    description:
      "UNESCO World Heritage Site, largest mangrove forest in the world. Home to Royal Bengal Tigers, diverse wildlife, and unique riverine ecosystem.",
    location: {
      city: "South 24 Parganas",
      state: "West Bengal",
      country: "India",
      coordinates: { lat: 21.9497, lng: 88.9187 },
      address: "Sundarbans, West Bengal, India",
    },
    rating: 4.5,
    reviews: 29000,
    entryFee: "₹100-300, Boat safari ₹2000-5000",
    timings: "October to March (Open season)",
    bestTimeToVisit: "November to February",
    image: "https://images.unsplash.com/photo-1564760055775-d63b17a55c44?w=800",
    highlights: [
      "Royal Bengal Tiger",
      "Mangrove forests",
      "Boat safaris",
      "Crocodiles",
      "River dolphins",
      "Watchtowers",
      "Unique ecosystem",
    ],
    activities: [
      "Boat safari",
      "Bird watching",
      "Village tours",
      "Wildlife spotting",
      "Photography",
      "Watchtower visits",
    ],
    nearbyAttractions: [
      { name: "Kolkata", distance: "110 km" },
      { name: "Sajnekhali", distance: "Base for tours" },
    ],
    howToReach: "Kolkata Airport 110 km, Canning Station 48 km, Boat from Godkhali/Sonakhali",
    tips: [
      "Book package tours",
      "Tiger sightings rare",
      "Carry mosquito repellent",
      "Respect wildlife zones",
      "Stay in eco-resorts",
    ],
    contactNumber: "+91-3218-255221",
    website: "https://www.sundarbansnationalpark.com",
    trending: true,
    trendingRank: 23,
    popularity: 74,
  },

  {
    name: "Konark Sun Temple",
    category: "Historical",
    description:
      "UNESCO World Heritage Site, 13th-century Sun Temple shaped as colossal chariot. Masterpiece of Kalinga architecture with intricate carvings and erotic sculptures.",
    location: {
      city: "Konark",
      state: "Odisha",
      country: "India",
      coordinates: { lat: 19.8876, lng: 86.0945 },
      address: "Konark, Odisha, India",
    },
    rating: 4.6,
    reviews: 41000,
    entryFee: "₹40 Indians, ₹600 Foreigners",
    timings: "6 AM - 8 PM",
    bestTimeToVisit: "October to March",
    image: "https://images.unsplash.com/photo-1609416917477-fde942239fbf?w=800",
    highlights: [
      "Chariot-shaped temple",
      "24 carved wheels",
      "Intricate sculptures",
      "Erotic carvings",
      "UNESCO site",
      "Konark Dance Festival",
    ],
    activities: [
      "Temple exploration",
      "Photography",
      "Archaeological museum",
      "Beach visit",
      "Cultural festivals",
    ],
    nearbyAttractions: [
      { name: "Puri", distance: "35 km" },
      { name: "Chandrabhaga Beach", distance: "3 km" },
    ],
    howToReach: "Bhubaneswar Airport 65 km, Puri Station 35 km, Well connected by road",
    tips: [
      "Visit early morning",
      "Hire guide for architecture details",
      "Attend dance festival in December",
      "Combine with Puri trip",
    ],
    contactNumber: "+91-6758-236821",
    website: "https://www.odishatourism.gov.in",
    trending: true,
    trendingRank: 24,
    popularity: 78,
  },

  {
    name: "Meenakshi Temple",
    category: "Religious",
    description:
      "Historic Hindu temple dedicated to Goddess Meenakshi, a form of Parvati. Famous for towering gopurams with thousands of colorful sculptures and grand architecture.",
    location: {
      city: "Madurai",
      state: "Tamil Nadu",
      country: "India",
      coordinates: { lat: 9.9195, lng: 78.1193 },
      address: "Madurai, Tamil Nadu, India",
    },
    rating: 4.8,
    reviews: 89000,
    entryFee: "Free, Camera ₹50",
    timings: "5 AM - 12:30 PM, 4 PM - 10 PM",
    bestTimeToVisit: "October to March",
    image: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800",
    highlights: [
      "14 towering gopurams",
      "Thousand Pillar Hall",
      "Golden lotus tank",
      "Evening ceremony",
      "Dravidian architecture",
      "Colorful sculptures",
    ],
    activities: [
      "Temple darshan",
      "Evening ceremony viewing",
      "Photography (exterior)",
      "Art hall visit",
      "Shopping in streets",
    ],
    nearbyAttractions: [
      { name: "Thirumalai Nayak Palace", distance: "2 km" },
      { name: "Gandhi Museum", distance: "5 km" },
    ],
    howToReach: "Madurai Airport 10 km, Madurai Junction Station 2 km, Well connected by road",
    tips: [
      "Dress modestly",
      "Remove footwear",
      "Visit during evening ceremony",
      "Photography restricted inside",
      "Explore streets around temple",
    ],
    contactNumber: "+91-452-2345151",
    website: "https://www.maduraimeenakshi.org",
    trending: true,
    trendingRank: 25,
    popularity: 86,
  },

  {
    name: "Agra Fort",
    category: "Historical",
    description:
      "UNESCO World Heritage Site, massive red sandstone fort built by Mughal Emperor Akbar. Houses palaces, mosques, and halls with Yamuna River views.",
    location: {
      city: "Agra",
      state: "Uttar Pradesh",
      country: "India",
      coordinates: { lat: 27.1795, lng: 78.0211 },
      address: "Rakabganj, Agra, Uttar Pradesh 282003",
    },
    rating: 4.6,
    reviews: 67000,
    entryFee: "₹50 Indians, ₹650 Foreigners",
    timings: "Sunrise to Sunset",
    bestTimeToVisit: "October to March",
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800",
    highlights: [
      "Jahangir Palace",
      "Khas Mahal",
      "Sheesh Mahal",
      "Diwan-i-Khas",
      "Taj Mahal view",
      "Mughal architecture",
    ],
    activities: [
      "Fort exploration",
      "Photography",
      "Guided tours",
      "Sound and light show",
      "History learning",
    ],
    nearbyAttractions: [
      { name: "Taj Mahal", distance: "2.5 km" },
      { name: "Itmad-ud-Daulah", distance: "7 km" },
    ],
    howToReach: "Agra Airport 13 km, Agra Cantt Station 6 km, Same as Taj Mahal",
    tips: [
      "Combine with Taj Mahal visit",
      "Hire audio guide",
      "Photography allowed",
      "Allow 2-3 hours",
      "View Taj from fort",
    ],
    contactNumber: "+91-562-2226431",
    website: "https://www.asi.nic.in",
    trending: true,
    trendingRank: 26,
    popularity: 83,
  },

  {
    name: "Red Fort Delhi",
    category: "Historical",
    description:
      "UNESCO World Heritage Site, iconic red sandstone fort built by Shah Jahan. Venue for Prime Minister's Independence Day speech. Symbol of India's sovereignty.",
    location: {
      city: "Delhi",
      state: "Delhi",
      country: "India",
      coordinates: { lat: 28.6562, lng: 77.241 },
      address: "Netaji Subhash Marg, Chandni Chowk, New Delhi 110006",
    },
    rating: 4.5,
    reviews: 93000,
    entryFee: "₹35 Indians, ₹500 Foreigners",
    timings: "9:30 AM - 4:30 PM (Closed Mondays)",
    bestTimeToVisit: "October to March",
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800",
    highlights: [
      "Lahori Gate",
      "Diwan-i-Am",
      "Diwan-i-Khas",
      "Rang Mahal",
      "Light and sound show",
      "Independence Day venue",
    ],
    activities: [
      "Fort exploration",
      "Museum visits",
      "Light show",
      "Photography",
      "Historical tours",
    ],
    nearbyAttractions: [
      { name: "Chandni Chowk", distance: "Adjacent" },
      { name: "Jama Masjid", distance: "500 m" },
    ],
    howToReach: "Chandni Chowk Metro, New Delhi Station 6 km, IGI Airport 20 km",
    tips: [
      "Visit early to avoid crowds",
      "Attend light show evening",
      "Combine with Old Delhi walk",
      "Chandni Chowk food tour",
    ],
    contactNumber: "+91-11-23277705",
    website: "https://www.delhitourism.gov.in",
    trending: true,
    trendingRank: 27,
    popularity: 85,
  },

  {
    name: "Gateway of India",
    category: "Historical",
    description:
      "Iconic arch-monument built during British Raj, overlooking Arabian Sea. Mumbai's most photographed landmark and starting point for harbor cruises.",
    location: {
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
      coordinates: { lat: 18.922, lng: 72.8347 },
      address: "Apollo Bandar, Colaba, Mumbai, Maharashtra 400001",
    },
    rating: 4.4,
    reviews: 105000,
    entryFee: "Free, Ferry to Elephanta ₹200",
    timings: "Open all day, best at evening",
    bestTimeToVisit: "November to February",
    image: "https://images.unsplash.com/photo-1566552881560-0be862a7c445?w=800",
    highlights: [
      "Indo-Saracenic architecture",
      "Arabian Sea views",
      "Elephant Caves ferry point",
      "Taj Mahal Palace Hotel view",
      "Street food",
    ],
    activities: [
      "Photography",
      "Elephanta Caves ferry",
      "Sunset viewing",
      "Shopping",
      "Boat rides",
      "Food tasting",
    ],
    nearbyAttractions: [
      { name: "Elephanta Caves", distance: "Ferry 1 hour" },
      { name: "Colaba Causeway", distance: "Walking" },
    ],
    howToReach: "CST Station 3 km, Mumbai Airport 26 km, Churchgate Metro 2 km",
    tips: [
      "Visit at sunset",
      "Take ferry to Elephanta",
      "Beware of touts",
      "Try street food nearby",
      "Visit Taj Hotel for views",
    ],
    contactNumber: "+91-22-22163737",
    website: "https://www.maharashtratourism.gov.in",
    trending: true,
    trendingRank: 28,
    popularity: 84,
  },

  {
    name: "Sanchi Stupa",
    category: "Historical",
    description:
      "UNESCO World Heritage Site, oldest stone structure in India and Buddhist complex built by Emperor Ashoka. Famous for hemispherical dome and ornate gateways.",
    location: {
      city: "Sanchi",
      state: "Madhya Pradesh",
      country: "India",
      coordinates: { lat: 23.4793, lng: 77.7395 },
      address: "Sanchi, Madhya Pradesh, India",
    },
    rating: 4.6,
    reviews: 28000,
    entryFee: "₹40 Indians, ₹600 Foreigners",
    timings: "Sunrise to Sunset",
    bestTimeToVisit: "October to March",
    image: "https://images.unsplash.com/photo-1609416917477-fde942239fbf?w=800",
    highlights: [
      "Great Stupa",
      "Ornate gateways (toranas)",
      "Ashoka Pillar",
      "Buddhist monuments",
      "Archaeological museum",
      "Ancient sculptures",
    ],
    activities: [
      "Stupa exploration",
      "Photography",
      "Museum visit",
      "Historical learning",
      "Meditation",
    ],
    nearbyAttractions: [
      { name: "Udayagiri Caves", distance: "60 km" },
      { name: "Bhopal", distance: "46 km" },
    ],
    howToReach: "Bhopal Airport 55 km, Bhopal Station 46 km, Sanchi Station 1 km",
    tips: [
      "Hire guide for Buddhist history",
      "Visit museum",
      "Peaceful place for meditation",
      "Combine with Bhopal trip",
    ],
    contactNumber: "+91-7480-266723",
    website: "https://www.mptourism.com",
    trending: true,
    trendingRank: 29,
    popularity: 73,
  },

  {
    name: "Mahabalipuram",
    category: "Historical",
    description:
      "UNESCO World Heritage Site with 7th-century rock-cut temples and sculptures. Ancient port city of Pallava dynasty featuring Shore Temple and Five Rathas.",
    location: {
      city: "Mahabalipuram",
      state: "Tamil Nadu",
      country: "India",
      coordinates: { lat: 12.6269, lng: 80.1992 },
      address: "Mahabalipuram, Tamil Nadu, India",
    },
    rating: 4.6,
    reviews: 53000,
    entryFee: "₹40 Indians, ₹600 Foreigners",
    timings: "6 AM - 6 PM",
    bestTimeToVisit: "November to February",
    image: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800",
    highlights: [
      "Shore Temple",
      "Five Rathas",
      "Arjuna's Penance",
      "Krishna's Butter Ball",
      "Beach",
      "Rock-cut caves",
      "Lighthouses",
    ],
    activities: [
      "Temple exploration",
      "Beach relaxation",
      "Photography",
      "Sculpture viewing",
      "Surfing",
      "Shopping handicrafts",
    ],
    nearbyAttractions: [
      { name: "Chennai", distance: "60 km" },
      { name: "Pondicherry", distance: "105 km" },
    ],
    howToReach: "Chennai Airport 60 km, Chengalpattu Station 29 km, ECR from Chennai",
    tips: [
      "Visit early to avoid heat",
      "Combine monuments with beach",
      "Buy stone sculptures",
      "Try fresh seafood",
      "Spend full day",
    ],
    contactNumber: "+91-44-27443845",
    website: "https://www.tamilnadutourism.tn.gov.in",
    trending: true,
    trendingRank: 30,
    popularity: 80,
  },
];

// MongoDB Connection and Seeding Function
async function seedDatabase() {
  const client = new MongoClient(MONGODB_URI);

  try {
    console.log("Connecting to MongoDB...");
    await client.connect();
    console.log("Connected successfully to MongoDB!");

    const db = client.db(DB_NAME);
    const collection = db.collection("destinations");

    // Clear existing trending destinations
    console.log("Clearing existing trending destinations...");
    await collection.deleteMany({ trending: true });

    console.log("Preparing destination media, maps, and weather metadata...");
    const destinationsToInsert = [];
    for (const destination of top30TrendingDestinations) {
      const clone = JSON.parse(JSON.stringify(destination));
      // Sequential to respect API rate limits
      // eslint-disable-next-line no-await-in-loop
      await enrichDestination(clone, { includeRawWeather: false });
      destinationsToInsert.push(clone);
    }

    // Insert new trending destinations
    console.log("Inserting 30 new trending destinations...");
    const result = await collection.insertMany(destinationsToInsert);

    console.log(`\n✅ Successfully inserted ${result.insertedCount} trending destinations!`);
    console.log("\n📊 Summary:");
    console.log(`Total destinations: ${result.insertedCount}`);
    console.log("\nTop 5 Trending:");
    destinationsToInsert.slice(0, 5).forEach((dest, index) => {
      console.log(
        `${index + 1}. ${dest.name} - ${dest.city}, ${dest.state} (Rating: ${dest.rating})`
      );
    });

    // Verify insertion
    const count = await collection.countDocuments({ trending: true });
    console.log(`\n✓ Verified: ${count} trending destinations in database`);
  } catch (error) {
    console.error("❌ Error seeding database:", error);
    process.exit(1);
  } finally {
    await client.close();
    console.log("\n👋 Database connection closed.");
  }
}

// Run the seeding function
if (require.main === module) {
  seedDatabase();
}

module.exports = { top30TrendingDestinations, seedDatabase };
