const destinations = [
  {
    name: "Taj Mahal",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxIpmZZCuhBToZ8D0c6sN05VYt7HGVz3dLFRIyXgpieinHTfsE7wqwWuavZ6bbB-7kWIL_btkKSDrkqmJOu015pUTe2VhioqTwCgI7TznpF40XPxw6wHv8YRz_pcKWRYJmcJ_s=s1360-w1360-h1020-rw",
    location: { city: "Agra", state: "Uttar Pradesh", country: "India" },
    description:
      "The Taj Mahal is an ivory-white marble mausoleum, built by Mughal emperor Shah Jahan in memory of his wife Mumtaz Mahal.",
    nearbyAttractions: [
      { name: "Agra Fort", distance: "2.5 km" },
      { name: "Mehtab Bagh", distance: "7 km" },
      { name: "Fatehpur Sikri", distance: "40 km" },
      { name: "Itimad-ud-Daulah", distance: "6 km" },
      { name: "Akbar's Tomb", distance: "10 km" },
      { name: "Jama Masjid", distance: "5 km" },
      { name: "Chini Ka Rauza", distance: "8 km" },
      { name: "Anguri Bagh", distance: "2.5 km" },
      { name: "Moti Masjid", distance: "2.5 km" },
      { name: "Taj Museum", distance: "0.5 km" },
    ],
  },
  {
    name: "Jaipur - The Pink City",
    image: "https://static.toiimg.com/thumb/107164817/Jaipur.jpg?width=1200&height=900",
    location: { city: "Jaipur", state: "Rajasthan", country: "India" },
    description:
      "Jaipur is known as the Pink City due to its distinctively colored buildings. Famous for stunning palaces, forts, and bazaars.",
    nearbyAttractions: [
      { name: "Amber Fort", distance: "11 km" },
      { name: "Hawa Mahal", distance: "4 km" },
      { name: "City Palace", distance: "4 km" },
      { name: "Jantar Mantar", distance: "4 km" },
      { name: "Nahargarh Fort", distance: "15 km" },
      { name: "Jaigarh Fort", distance: "12 km" },
      { name: "Jal Mahal", distance: "6 km" },
      { name: "Albert Hall Museum", distance: "5 km" },
      { name: "Birla Mandir", distance: "8 km" },
      { name: "Galtaji Temple", distance: "10 km" },
    ],
  },
  {
    name: "Goa Beaches",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSy2T-4vDkV05zZ4YtNbsIQkuDgTQLqBYpe3IarZtPZtdJsE5S7y5Vu_oqs-991usAOm1PYgza8VcguPYd6HXs7La4pCgiZ7sz1NgC32HYFH-w5ampQ9zzar_x_fl-wkZaK27_s=w675-h390-n-k-no",
    location: { city: "Goa", state: "Goa", country: "India" },
    description:
      "Goa is renowned for pristine beaches, vibrant nightlife, Portuguese heritage, and laid-back atmosphere.",
    nearbyAttractions: [
      { name: "Calangute Beach", distance: "15 km" },
      { name: "Baga Beach", distance: "16 km" },
      { name: "Fort Aguada", distance: "18 km" },
      { name: "Basilica of Bom Jesus", distance: "10 km" },
      { name: "Dudhsagar Falls", distance: "60 km" },
      { name: "Anjuna Beach", distance: "20 km" },
      { name: "Chapora Fort", distance: "22 km" },
      { name: "Palolem Beach", distance: "70 km" },
      { name: "Se Cathedral", distance: "10 km" },
      { name: "Vagator Beach", distance: "21 km" },
    ],
  },
  {
    name: "Varanasi (Kashi)",
    image:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcT8qoYxE6WuCGjiPgfRNTXF1FlLTCHkK4UVyoyJhGl8wj5nQrsKX1v19rPyqrjZ1R6cSqvQhfAry8GdzE_pHmVQuZ0&s=19",
    location: { city: "Varanasi", state: "Uttar Pradesh", country: "India" },
    description:
      "Varanasi is the spiritual capital of India, famous for ghats, temples, and the Ganga Aarti.",
    nearbyAttractions: [
      { name: "Kashi Vishwanath Temple", distance: "1 km" },
      { name: "Dashashwamedh Ghat", distance: "1 km" },
      { name: "Assi Ghat", distance: "2 km" },
      { name: "Sarnath", distance: "10 km" },
      { name: "Ramnagar Fort", distance: "14 km" },
      { name: "Manikarnika Ghat", distance: "1.5 km" },
      { name: "Sankat Mochan Temple", distance: "5 km" },
      { name: "BHU", distance: "6 km" },
      { name: "Tulsi Manas Mandir", distance: "4 km" },
      { name: "Bharat Mata Mandir", distance: "3 km" },
    ],
  },
  {
    name: "Kerala Backwaters",
    image:
      "https://www.google.com/imgres?q=kerala%20backwaters&imgurl=https%3A%2F%2Fwww.jacadatravel.com%2F_next%2Fimage%2F%3Furl%3Dhttps%253A%252F%252Fcdn.jacadatravel.com%252Fwp-content%252Fuploads%252Fbis-images%252F470032%252FKerala-AdobeStock_164621341-2-1600x900-f50_50.jpg%26w%3D3840%26q%3D100&imgrefurl=https%3A%2F%2Fwww.jacadatravel.com%2Findian-subcontinent%2Findia%2Fkeralan-backwaters%2F&docid=I7JWfNlSKIWFGM&tbnid=fN692fa7UtJkbM&vet=12ahUKEwiwlcOq0I2RAxW-na8BHRv1AB4QM3oECE4QAA..i&w=1600&h=900&hcb=2&ved=2ahUKEwiwlcOq0I2RAxW-na8BHRv1AB4QM3oECE4QAA",
    location: { city: "Alleppey", state: "Kerala", country: "India" },
    description:
      "A network of interconnected canals, rivers, lakes, and inlets along Kerala's coast, famous for houseboats.",
    nearbyAttractions: [
      { name: "Alleppey Beach", distance: "2 km" },
      { name: "Marari Beach", distance: "15 km" },
      { name: "Kumarakom Bird Sanctuary", distance: "30 km" },
      { name: "Vembanad Lake", distance: "5 km" },
      { name: "Krishnapuram Palace", distance: "47 km" },
      { name: "Ambalapuzha Temple", distance: "14 km" },
      { name: "Pathiramanal Island", distance: "13 km" },
      { name: "Kuttanad", distance: "20 km" },
      { name: "Punnamada Lake", distance: "4 km" },
      { name: "Revi Karunakaran Museum", distance: "3 km" },
    ],
  },
  {
    name: "Ladakh - Land of High Passes",
    image:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcS4lvKhMN4OdQkB3EICfK6tvgxNDnSdzfFzvWbh9vz3ZcW-gGm7uAxQ1MoElx3NBoBsIohc92r1FFHWTXBwm34rC9A&s=19",
    location: { city: "Leh", state: "Ladakh", country: "India" },
    description:
      "High-altitude desert with stunning landscapes, Buddhist monasteries, and pristine lakes.",
    nearbyAttractions: [
      { name: "Pangong Lake", distance: "160 km" },
      { name: "Nubra Valley", distance: "120 km" },
      { name: "Thiksey Monastery", distance: "19 km" },
      { name: "Leh Palace", distance: "2 km" },
      { name: "Shanti Stupa", distance: "5 km" },
      { name: "Magnetic Hill", distance: "30 km" },
      { name: "Hemis Monastery", distance: "40 km" },
      { name: "Khardung La", distance: "40 km" },
      { name: "Spituk Gompa", distance: "8 km" },
      { name: "Hall of Fame", distance: "6 km" },
    ],
  },
  {
    name: "Rishikesh - Yoga Capital",
    image:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQEhbTgpsKgm1pU7d_k0UGJqx8QabKFD9MgA5JNrSjBOQeLud3ZHdyEq0oD6eCt2ctazBrzVwvGEV3Y0f8SquJQqks&s=19",
    location: { city: "Rishikesh", state: "Uttarakhand", country: "India" },
    description:
      "Spiritual town in Himalayan foothills on Ganges River, known for yoga, temples, and adventure sports.",
    nearbyAttractions: [
      { name: "Lakshman Jhula", distance: "2 km" },
      { name: "Ram Jhula", distance: "3 km" },
      { name: "Triveni Ghat", distance: "5 km" },
      { name: "Beatles Ashram", distance: "4 km" },
      { name: "Parmarth Niketan", distance: "3.5 km" },
      { name: "Neer Garh Waterfall", distance: "8 km" },
      { name: "Vashishta Gufa", distance: "22 km" },
      { name: "Kunjapuri Temple", distance: "25 km" },
      { name: "Rajaji National Park", distance: "18 km" },
      { name: "Shivpuri", distance: "16 km" },
    ],
  },
  {
    name: "Darjeeling - Queen of Hills",
    image:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcTpV_Pg_9GOEqGv86Qqs2uO5neQNkQtPnuUyHP-fSmH3t0qt6WveYq4ytsljSSH1Yy3QDgNKlDJHW0kRunjt8dMnnHA&s=19",
    location: { city: "Darjeeling", state: "West Bengal", country: "India" },
    description:
      "Picturesque hill station famous for tea plantations, Kanchenjunga views, and the Toy Train.",
    nearbyAttractions: [
      { name: "Tiger Hill", distance: "11 km" },
      { name: "Batasia Loop", distance: "5 km" },
      { name: "Ghoom Monastery", distance: "8 km" },
      { name: "Peace Pagoda", distance: "2 km" },
      { name: "Himalayan Zoo", distance: "3 km" },
      { name: "Happy Valley Tea Estate", distance: "3 km" },
      { name: "Rock Garden", distance: "4 km" },
      { name: "Observatory Hill", distance: "1 km" },
      { name: "Mahakal Temple", distance: "1.5 km" },
      { name: "Nightingale Park", distance: "2 km" },
    ],
  },
  {
    name: "Andaman Islands",
    image:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcRAC52E_JE8jjWGps9xOYF00uJOafIArlyXRZIbjjYb7_AxbntYq-lgqXK-6M9aevYePAPLp-i8BhYMiwe1HxoRqrQ&s=19",
    location: { city: "Port Blair", state: "Andaman", country: "India" },
    description:
      "Tropical islands with pristine beaches, turquoise waters, coral reefs, and rich marine life.",
    nearbyAttractions: [
      { name: "Havelock Island", distance: "50 km" },
      { name: "Neil Island", distance: "40 km" },
      { name: "Cellular Jail", distance: "1 km" },
      { name: "Radhanagar Beach", distance: "55 km" },
      { name: "Ross Island", distance: "3 km" },
      { name: "Elephant Beach", distance: "52 km" },
      { name: "North Bay Island", distance: "5 km" },
      { name: "Chidiya Tapu", distance: "25 km" },
      { name: "Baratang Caves", distance: "100 km" },
      { name: "Wandoor Beach", distance: "25 km" },
    ],
  },
  {
    name: "Mysore Palace",
    image:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcSuq7b2bJxPQwOMfK2gh1eVNlkuru7d3HyGsZTurLM6BEYLmXxbuRrYqFHrIwTF3s6PONnSX1Y8R6cU9_HopDIIlFUx&s=19",
    location: { city: "Mysore", state: "Karnataka", country: "India" },
    description: "Magnificent Indo-Saracenic palace, one of India's most visited monuments.",
    nearbyAttractions: [
      { name: "Chamundi Hill", distance: "13 km" },
      { name: "Brindavan Gardens", distance: "20 km" },
      { name: "Mysore Zoo", distance: "2 km" },
      { name: "St. Philomena's Church", distance: "3 km" },
      { name: "Jaganmohan Palace", distance: "1.5 km" },
      { name: "Karanji Lake", distance: "3 km" },
      { name: "Rail Museum", distance: "2 km" },
      { name: "Lalitha Mahal", distance: "5 km" },
      { name: "Ranganathittu Bird Sanctuary", distance: "16 km" },
      { name: "Srirangapatna", distance: "15 km" },
    ],
  },
  {
    name: "Hampi",
    image:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQ_8bmllUjuB6NCL66IryUEdSEmcT7UGDqpxo2fsWnaUVtCNYmwP9QgJm8tE10HmpLIoBOEaKUtXdXKkGtPxIK4FNQ&s=19",
    location: { city: "Hampi", state: "Karnataka", country: "India" },
    description:
      "UNESCO World Heritage Site with ruins of Vijayanagara Empire. Ancient temples and massive boulders.",
    nearbyAttractions: [
      { name: "Virupaksha Temple", distance: "0.5 km" },
      { name: "Vittala Temple", distance: "2 km" },
      { name: "Stone Chariot", distance: "2 km" },
      { name: "Lotus Mahal", distance: "3 km" },
      { name: "Elephant Stables", distance: "3.2 km" },
      { name: "Matanga Hill", distance: "1 km" },
      { name: "Hemakuta Hill", distance: "0.8 km" },
      { name: "Achyutaraya Temple", distance: "1.5 km" },
      { name: "Queen's Bath", distance: "3.5 km" },
      { name: "Tungabhadra Dam", distance: "15 km" },
    ],
  },
  {
    name: "Udaipur - City of Lakes",
    image:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcSOpyumgKVnx5kzfOk0mftrdgZupK_KLizFkdGjtCxzwfp9IJ0faaeFEDOfNRVzEN6huBY-GOiJzy1yMxJLs3hwyvY&s=19",
    location: { city: "Udaipur", state: "Rajasthan", country: "India" },
    description:
      "Romantic city with beautiful palaces, lakes, and havelis. Known as Venice of the East.",
    nearbyAttractions: [
      { name: "City Palace", distance: "0.5 km" },
      { name: "Lake Pichola", distance: "1 km" },
      { name: "Jag Mandir", distance: "1.5 km" },
      { name: "Saheliyon Ki Bari", distance: "4 km" },
      { name: "Fateh Sagar Lake", distance: "5 km" },
      { name: "Monsoon Palace", distance: "10 km" },
      { name: "Bagore Ki Haveli", distance: "0.5 km" },
      { name: "Jagdish Temple", distance: "0.2 km" },
      { name: "Vintage Car Museum", distance: "2 km" },
      { name: "Eklingji Temple", distance: "22 km" },
    ],
  },
  {
    name: "Munnar",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwA6LSbFpCXI-bkP2_H1WI2mXNeJ5FlFa_h2DboHWGv5ACzGkbDxgF3zMQQGuWI8htlxybocEUXXlzG20Jc0ymizgKDyKo-m0Awb8jzBGdLCk13vjtG4Ntu4Pecu4rED6X7BnAd=w675-h390-n-k-no",
    location: { city: "Munnar", state: "Kerala", country: "India" },
    description:
      "Picturesque hill station in Western Ghats, famous for tea plantations and misty mountains.",
    nearbyAttractions: [
      { name: "Tea Gardens", distance: "2 km" },
      { name: "Mattupetty Dam", distance: "13 km" },
      { name: "Eravikulam National Park", distance: "15 km" },
      { name: "Anamudi Peak", distance: "20 km" },
      { name: "Echo Point", distance: "15 km" },
      { name: "Tea Museum", distance: "2 km" },
      { name: "Top Station", distance: "32 km" },
      { name: "Kundala Lake", distance: "20 km" },
      { name: "Attukad Waterfalls", distance: "9 km" },
      { name: "Pothamedu View Point", distance: "6 km" },
    ],
  },
  {
    name: "Coorg",
    image:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcSYXVRIfXaOGdt2Qxv717A4zi7N1eLeo4XCbxZlFGyJyKDc860-V1hH9Pv7oBTCPEiKZwMXW2vpFX00dTbhCoG0mg8G&s=19",
    location: { city: "Coorg", state: "Karnataka", country: "India" },
    description:
      "Scotland of India, known for coffee plantations, lush green hills, and waterfalls.",
    nearbyAttractions: [
      { name: "Abbey Falls", distance: "8 km" },
      { name: "Raja's Seat", distance: "1 km" },
      { name: "Dubare Elephant Camp", distance: "30 km" },
      { name: "Talakaveri", distance: "45 km" },
      { name: "Golden Temple (Bylakuppe)", distance: "35 km" },
      { name: "Mandalpatti", distance: "20 km" },
      { name: "Nagarhole National Park", distance: "90 km" },
      { name: "Iruppu Falls", distance: "80 km" },
      { name: "Nisargadhama", distance: "28 km" },
      { name: "Omkareshwara Temple", distance: "1 km" },
    ],
  },
  {
    name: "Srinagar",
    image:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcSmGP95zaU947n7wiSC1oc2afEDVje1IqWkCoiGhkb1HaBl8a3_PJQAztYN-2nvnTomecCs3qI-S1yMyGY4WuGXaNU&s=19",
    location: { city: "Srinagar", state: "Jammu & Kashmir", country: "India" },
    description: "Famous for Dal Lake, houseboats, Mughal gardens, and stunning Himalayan views.",
    nearbyAttractions: [
      { name: "Dal Lake", distance: "0 km" },
      { name: "Shalimar Bagh", distance: "15 km" },
      { name: "Nishat Bagh", distance: "12 km" },
      { name: "Shankaracharya Temple", distance: "5 km" },
      { name: "Tulip Garden", distance: "8 km" },
      { name: "Pari Mahal", distance: "10 km" },
      { name: "Hazratbal Shrine", distance: "10 km" },
      { name: "Gulmarg", distance: "50 km" },
      { name: "Pahalgam", distance: "90 km" },
      { name: "Sonamarg", distance: "80 km" },
    ],
  },
  {
    name: "Manali",
    image:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcTKoROBq7Ih5MRq3qE9NwGd4HKBXjXC54cpMnNH-4UDlLCja2guhY-Y4Xs281W_quKFkra1t7JTexHeedswRje5svA&s=19",
    location: { city: "Manali", state: "Himachal Pradesh", country: "India" },
    description: "High-altitude Himalayan resort town, gateway for adventure sports and Ladakh.",
    nearbyAttractions: [
      { name: "Hadimba Temple", distance: "2 km" },
      { name: "Solang Valley", distance: "13 km" },
      { name: "Rohtang Pass", distance: "51 km" },
      { name: "Old Manali", distance: "3 km" },
      { name: "Vashisht Hot Springs", distance: "3 km" },
      { name: "Jogini Falls", distance: "4 km" },
      { name: "Manu Temple", distance: "3 km" },
      { name: "Naggar Castle", distance: "20 km" },
      { name: "Atal Tunnel", distance: "28 km" },
      { name: "Beas River", distance: "1 km" },
    ],
  },
  {
    name: "Pondicherry",
    image:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcRGryPItd-amOC6IuSXS3ifO8cqBpS99_F-JrS0mPglhCTgg54pZYBHD6nP7BCSo9PdN17tilo4tPxb-3qqDUmWJUw&s=19",
    location: { city: "Pondicherry", state: "Puducherry", country: "India" },
    description:
      "Former French colony with distinct French Quarter, promenade, and spiritual Auroville.",
    nearbyAttractions: [
      { name: "Promenade Beach", distance: "0 km" },
      { name: "Auroville", distance: "12 km" },
      { name: "Sri Aurobindo Ashram", distance: "1 km" },
      { name: "Paradise Beach", distance: "8 km" },
      { name: "Manakula Vinayagar Temple", distance: "1 km" },
      { name: "French War Memorial", distance: "0.5 km" },
      { name: "Basilica of Sacred Heart", distance: "2 km" },
      { name: "Serenity Beach", distance: "5 km" },
      { name: "Botanical Garden", distance: "3 km" },
      { name: "Chunnambar Boat House", distance: "7 km" },
    ],
  },
  {
    name: "Shillong",
    image:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcTG60aDUuBMY7Yl9z6yA5sDvdj9hysBHiPpPZRzasMILmoGuDrPiZuHITLq6r6h8a_Tal5znWdEk09Et80PAACHo8Y&s=19",
    location: { city: "Shillong", state: "Meghalaya", country: "India" },
    description:
      "Scotland of the East, known for rolling hills, waterfalls, and vibrant music scene.",
    nearbyAttractions: [
      { name: "Umiam Lake", distance: "15 km" },
      { name: "Elephant Falls", distance: "12 km" },
      { name: "Shillong Peak", distance: "10 km" },
      { name: "Don Bosco Museum", distance: "3 km" },
      { name: "Ward's Lake", distance: "1 km" },
      { name: "Laitlum Canyons", distance: "25 km" },
      { name: "Cherrapunji", distance: "54 km" },
      { name: "Mawlynnong", distance: "78 km" },
      { name: "Dawki River", distance: "85 km" },
      { name: "Living Root Bridges", distance: "60 km" },
    ],
  },
  {
    name: "Rann of Kutch",
    image:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQ3tOG1zFF3ilTMO_laHu9LkXy7Xlnj46GoRSa8hqEeCPlsFANkdCg3iuGUv_Y3uFZnWL4b-hTVrqa3EtzZEEHE1og&s=19",
    location: { city: "Kutch", state: "Gujarat", country: "India" },
    description: "World's largest salt desert, famous for the Rann Utsav and white salt plains.",
    nearbyAttractions: [
      { name: "White Desert", distance: "0 km" },
      { name: "Kala Dungar", distance: "45 km" },
      { name: "Kutch Fossil Park", distance: "60 km" },
      { name: "Vijay Vilas Palace", distance: "80 km" },
      { name: "Mandvi Beach", distance: "85 km" },
      { name: "Aina Mahal", distance: "75 km" },
      { name: "Prag Mahal", distance: "75 km" },
      { name: "Narayan Sarovar", distance: "100 km" },
      { name: "Dholavira", distance: "200 km" },
      { name: "Bhuj", distance: "75 km" },
    ],
  },
  {
    name: "Kolkata",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxKxU3d0iDQDW_6TTxcl-TEbnYv-ItMaZM8OfB6eKeTW9dPBkWEst5M1dM99mhn2kFXYszQoVbiPiHJAGtTE4Y8zmC2qTq4OGbrrjF3dxghKSdthMNJuBlh8A_GHSFEd5gE-I1v=w675-h390-n-k-no",
    location: { city: "Kolkata", state: "West Bengal", country: "India" },
    description: "City of Joy, famous for colonial architecture, literature, and street food.",
    nearbyAttractions: [
      { name: "Victoria Memorial", distance: "2 km" },
      { name: "Howrah Bridge", distance: "4 km" },
      { name: "Dakshineswar Kali Temple", distance: "12 km" },
      { name: "Belur Math", distance: "10 km" },
      { name: "Indian Museum", distance: "1 km" },
      { name: "Kalighat Temple", distance: "5 km" },
      { name: "Science City", distance: "8 km" },
      { name: "Eco Park", distance: "15 km" },
      { name: "St. Paul's Cathedral", distance: "2 km" },
      { name: "Princep Ghat", distance: "3 km" },
    ],
  },
  {
    name: "Ooty",
    image:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcRsiBMAq9kNWgq4Bdi4uq6UMjqeoOT_m6MRrIPg8HIo_xTMmFiGB7zf44M-KJatx5cMbjjIA_lmhlZdmqGUr9fLgY0j&s=19",
    location: { city: "Ooty", state: "Tamil Nadu", country: "India" },
    description: "Queen of Hill Stations in Nilgiris, famous for botanical gardens and toy train.",
    nearbyAttractions: [
      { name: "Botanical Gardens", distance: "2 km" },
      { name: "Ooty Lake", distance: "1 km" },
      { name: "Doddabetta Peak", distance: "9 km" },
      { name: "Rose Garden", distance: "2 km" },
      { name: "Pykara Lake", distance: "20 km" },
      { name: "Emerald Lake", distance: "20 km" },
      { name: "Avalanche Lake", distance: "22 km" },
      { name: "Tea Museum", distance: "4 km" },
      { name: "St. Stephen's Church", distance: "2 km" },
      { name: "Mudumalai National Park", distance: "40 km" },
    ],
  },
  {
    name: "Tirupati",
    image:
      "https://www.google.com/imgres?q=tirupati&imgurl=https%3A%2F%2Fcdn.britannica.com%2F22%2F156222-050-BEE18768%2FSri-Venkateswara-Swamy-Temple-Tirumala-Tirupati-India.jpg&imgrefurl=https%3A%2F%2Fwww.britannica.com%2Fplace%2FTirupati&docid=RdaNDruvJsxUuM&tbnid=-G9lEaiu4bXVZM&vet=12ahUKEwi3rsKl0I2RAxVvaPUHHWwxBFsQM3oECCkQAA..i&w=1000&h=750&hcb=2&ved=2ahUKEwi3rsKl0I2RAxVvaPUHHWwxBFsQM3oECCkQAA",
    location: { city: "Tirupati", state: "Andhra Pradesh", country: "India" },
    description: "Home to the world-renowned Tirumala Venkateswara Temple.",
    nearbyAttractions: [
      { name: "Tirumala Temple", distance: "20 km" },
      { name: "Kapila Theertham", distance: "3 km" },
      { name: "Sri Govindaraja Swamy Temple", distance: "1 km" },
      { name: "Talakona Waterfalls", distance: "50 km" },
      { name: "Chandragiri Fort", distance: "15 km" },
      { name: "Sri Padmavathi Ammavari Temple", distance: "5 km" },
      { name: "Silathoranam", distance: "21 km" },
      { name: "Akasaganga Teertham", distance: "22 km" },
      { name: "Papavinasam", distance: "24 km" },
      { name: "Deer Park", distance: "25 km" },
    ],
  },
  {
    name: "Khajuraho",
    image:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQ4GI2R1FnGpWY8hko17NEdDvY36BG2ciFwcYZTTtRc1CoZLEMBobljURUnRoLJ6FNOV1ryrUmPi4PjYyuE63_MCHhy&s=19",
    location: { city: "Khajuraho", state: "Madhya Pradesh", country: "India" },
    description: "Famous for stunning temples adorned with intricate and erotic rock carvings.",
    nearbyAttractions: [
      { name: "Western Group of Temples", distance: "1 km" },
      { name: "Eastern Group of Temples", distance: "2 km" },
      { name: "Raneh Falls", distance: "20 km" },
      { name: "Panna National Park", distance: "25 km" },
      { name: "Pandav Falls", distance: "30 km" },
      { name: "Archaeological Museum", distance: "1 km" },
      { name: "Jain Temples", distance: "2 km" },
      { name: "Dulhadev Temple", distance: "3 km" },
      { name: "Chaturbhuj Temple", distance: "3 km" },
      { name: "Ken Gharial Sanctuary", distance: "25 km" },
    ],
  },
  {
    name: "Jaisalmer",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyrwdGmWgOSzTUGmpNw0nN8LSurweC7_FIVR6a_pndtv-IDmwCgGYNChde4Qju-TkIpG83yaJMXdugqDIM53o5MG_TBDiJBqHI67bnicniPVV9AUKWqXjlaXpAF0AUzTw1yaV8=w675-h390-n-k-no",
    location: { city: "Jaisalmer", state: "Rajasthan", country: "India" },
    description: "Golden City famous for its yellow sandstone architecture and living fort.",
    nearbyAttractions: [
      { name: "Jaisalmer Fort", distance: "0 km" },
      { name: "Sam Sand Dunes", distance: "40 km" },
      { name: "Patwon Ki Haveli", distance: "1 km" },
      { name: "Gadisar Lake", distance: "2 km" },
      { name: "Bada Bagh", distance: "6 km" },
      { name: "Kuldhara Village", distance: "18 km" },
      { name: "Tanot Mata Temple", distance: "120 km" },
      { name: "Desert National Park", distance: "40 km" },
      { name: "Jain Temples", distance: "0.5 km" },
      { name: "Nathmal Ki Haveli", distance: "0.5 km" },
    ],
  },
  {
    name: "Amritsar",
    image:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQ2_dPJzwnxGLS6rLOzpVy0nWV29n_JeQHekj1DSP1Tu9paJm2YZqrTp4fmQjrIs74rcBG34MRSLG8trs8m2gquJEs&s=19",
    location: { city: "Amritsar", state: "Punjab", country: "India" },
    description: "Spiritual heart of Sikhism, home to the Golden Temple and Wagah Border.",
    nearbyAttractions: [
      { name: "Golden Temple", distance: "0 km" },
      { name: "Jallianwala Bagh", distance: "0.5 km" },
      { name: "Wagah Border", distance: "30 km" },
      { name: "Partition Museum", distance: "1 km" },
      { name: "Gobindgarh Fort", distance: "2 km" },
      { name: "Durgiana Temple", distance: "1.5 km" },
      { name: "Ram Tirath", distance: "11 km" },
      { name: "Akal Takht", distance: "0 km" },
      { name: "Hall Bazaar", distance: "1 km" },
      { name: "Maharaja Ranjit Singh Museum", distance: "3 km" },
    ],
  },
  {
    name: "Gangtok",
    image:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQ0E5w5trotmFiXnnHPqtxLE3GA54Fvz0hA5Qap0RZl_3Tz1wxKVzCCQsX2oMXQW1lbZOvp3ie4uKnT4lDsyqAkRYI&s=19",
    location: { city: "Gangtok", state: "Sikkim", country: "India" },
    description: "Capital of Sikkim, known for cleanliness, Kanchenjunga views, and monasteries.",
    nearbyAttractions: [
      { name: "MG Marg", distance: "0 km" },
      { name: "Tsomgo Lake", distance: "40 km" },
      { name: "Nathula Pass", distance: "56 km" },
      { name: "Rumtek Monastery", distance: "24 km" },
      { name: "Ban Jhakri Falls", distance: "7 km" },
      { name: "Ganesh Tok", distance: "6 km" },
      { name: "Tashi View Point", distance: "8 km" },
      { name: "Enchey Monastery", distance: "3 km" },
      { name: "Baba Mandir", distance: "52 km" },
      { name: "Flower Exhibition Centre", distance: "2 km" },
    ],
  },
  {
    name: "Kodaikanal",
    image:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcSZHDiZsXBW-EP7YaBkcGgi_f8CulJ4JFrXNo8L-E5aAoMEpnASayOiLuiNlgbhs9vzGnatv1thtRPyGVcq8nnTSsc&s=19",
    location: { city: "Kodaikanal", state: "Tamil Nadu", country: "India" },
    description: "Princess of Hills, centered around a star-shaped lake.",
    nearbyAttractions: [
      { name: "Kodai Lake", distance: "0 km" },
      { name: "Coaker's Walk", distance: "1 km" },
      { name: "Bryant Park", distance: "1 km" },
      { name: "Pillar Rocks", distance: "7 km" },
      { name: "Silver Cascade Falls", distance: "8 km" },
      { name: "Green Valley View", distance: "5.5 km" },
      { name: "Dolphin's Nose", distance: "8 km" },
      { name: "Bear Shola Falls", distance: "3 km" },
      { name: "Guna Caves", distance: "8.5 km" },
      { name: "Berijam Lake", distance: "21 km" },
    ],
  },
  {
    name: "Nainital",
    image:
      "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcT4RcsJ-VerUWjLcJK_9bzV-xTUx_k3pMH8vnpKr29HX6djTTPt1IC_iHEF_rljvAACWA7PStfBx2osPZ6ZRyQ_yrM&s=19",
    location: { city: "Nainital", state: "Uttarakhand", country: "India" },
    description: "Lake District of India, built around the mango-shaped Naini Lake.",
    nearbyAttractions: [
      { name: "Naini Lake", distance: "0 km" },
      { name: "Naina Devi Temple", distance: "1 km" },
      { name: "Snow View Point", distance: "3 km" },
      { name: "Tiffin Top", distance: "4 km" },
      { name: "Eco Cave Gardens", distance: "2 km" },
      { name: "High Altitude Zoo", distance: "2 km" },
      { name: "Bhimtal", distance: "22 km" },
      { name: "Sattal", distance: "23 km" },
      { name: "Naukuchiatal", distance: "26 km" },
      { name: "Kainchi Dham", distance: "17 km" },
    ],
  },
  {
    name: "Gir National Park",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyy9wp3u4LKFPahn4EMOWIZwLRF6_IWkvPRHqkHGlzx4QdAUv5fUISmLRWaUmFIJvXC2KZlDQVEjFwiE65sU8qxVlDMEPnzrVeDSS0Ohjky9HuFIk1aQolw7bD2LKxdNnyBCzZI=s1360-w1360-h1020-rw",
    location: { city: "Sasan Gir", state: "Gujarat", country: "India" },
    description: "The only natural habitat of Asiatic Lions in the world.",
    nearbyAttractions: [
      { name: "Devalia Safari Park", distance: "12 km" },
      { name: "Somnath Temple", distance: "45 km" },
      { name: "Kamleshwar Dam", distance: "10 km" },
      { name: "Jamjir Waterfall", distance: "20 km" },
      { name: "Kankai Mata Temple", distance: "25 km" },
      { name: "Uparkot Fort", distance: "75 km" },
      { name: "Mahabat Maqbara", distance: "75 km" },
      { name: "Diu", distance: "65 km" },
      { name: "Tulsi Shyam", distance: "30 km" },
      { name: "Chorwad Beach", distance: "60 km" },
    ],
  },
  {
    name: "Sundarbans National Park",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSz4L0Mncx0ZsdxIUPPVJ4QrqspF8WccDzfTHjL4vtiddESwfOXB9gYCCyshZdzEJJ9kN3iIUqf-ddjZ-NXYPGKYoYdVvADLm55XrP1v0nlQCKbtwPd_G5Z3EKjkfBMuU_-uXKo=s1360-w1360-h1020-rw",
    location: { city: "Sundarbans", state: "West Bengal", country: "India" },
    description: "World's largest mangrove forest and home to Royal Bengal Tigers.",
    nearbyAttractions: [
      { name: "Sajnekhali Watch Tower", distance: "0 km" },
      { name: "Sudhanyakhali Watch Tower", distance: "10 km" },
      { name: "Dobanki Watch Tower", distance: "20 km" },
      { name: "Netidhopani", distance: "25 km" },
      { name: "Burirdabri", distance: "40 km" },
      { name: "Kanak", distance: "15 km" },
      { name: "Holiday Island", distance: "30 km" },
      { name: "Bhagabatpur Crocodile Project", distance: "50 km" },
      { name: "Piyali Island", distance: "70 km" },
      { name: "Bakkhali", distance: "100 km" },
    ],
  },
];

module.exports = destinations;
