const top30TrendingDestinations = [
  {
    name: "Taj Mahal",
    category: "Historical",
    description:
      "The Taj Mahal is an ivory-white marble mausoleum, built by Mughal emperor Shah Jahan in memory of his wife Mumtaz Mahal. One of the Seven Wonders of the World and UNESCO World Heritage Site, it stands as a timeless symbol of love and architectural brilliance.",
    location: {
      city: "Agra",
      state: "Uttar Pradesh",
      country: "India",
      coordinates: { lat: 27.1751, lng: 78.0421 },
      address: "Dharmapuri, Forest Colony, Tajganj, Agra, Uttar Pradesh 282001",
    },
    rating: 4.9,
    reviews: 125000,
    entryFee: "₹50 Indians, ₹1300 Foreigners",
    timings: "Sunrise to Sunset (Closed Fridays)",
    bestTimeToVisit: "October to March",
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800",
    highlights: [
      "UNESCO World Heritage Site",
      "Seven Wonders of the World",
      "White marble architecture",
      "Mughal Gardens",
      "Intricate inlay work",
    ],
    activities: ["Photography", "Heritage tours", "Sunrise viewing", "Garden walks"],
    nearbyAttractions: [
      { name: "Agra Fort", distance: "2.5 km" },
      { name: "Fatehpur Sikri", distance: "40 km" },
      { name: "Mehtab Bagh", distance: "7 km" },
      { name: "Tomb of Itimad-ud-Daulah", distance: "6 km" },
      { name: "Akbar's Tomb", distance: "10 km" },
      { name: "Jama Masjid", distance: "5 km" },
      { name: "Chini Ka Rauza", distance: "8 km" },
      { name: "Anguri Bagh", distance: "2.5 km" },
      { name: "Moti Masjid", distance: "2.5 km" },
      { name: "Taj Museum", distance: "0.5 km" },
    ],
    howToReach: "Agra Airport 13 km, Delhi Airport 230 km, Agra Cantt Station 6 km",
    tips: ["Book tickets online", "Visit on weekdays", "No food/tobacco inside", "Carry valid ID"],
    contactNumber: "+91-562-2227261",
    website: "https://www.tajmahal.gov.in",
    trending: true,
    trendingRank: 1,
    popularity: 100,
  },

  {
    name: "Jaipur - The Pink City",
    category: "Historical",
    description:
      "Jaipur, the capital of Rajasthan, is known as the Pink City due to its distinctively colored buildings. Famous for stunning palaces, forts, vibrant bazaars, and rich Rajasthani culture.",
    location: {
      city: "Jaipur",
      state: "Rajasthan",
      country: "India",
      coordinates: { lat: 26.9124, lng: 75.7873 },
      address: "Jaipur, Rajasthan, India",
    },
    rating: 4.7,
    reviews: 98000,
    entryFee: "₹200-500 per monument",
    timings: "9:00 AM - 5:00 PM",
    bestTimeToVisit: "October to March",
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800",
    highlights: [
      "Amber Fort",
      "Hawa Mahal",
      "City Palace",
      "Jantar Mantar UNESCO Site",
      "Jal Mahal",
      "Nahargarh Fort",
    ],
    activities: [
      "Elephant ride at Amber",
      "Hot air balloon ride",
      "Shopping for jewelry",
      "Traditional dinner with cultural show",
    ],
    nearbyAttractions: [
      { name: "City Palace", distance: "4 km" },
      { name: "Jantar Mantar", distance: "4.5 km" },
      { name: "Nahargarh Fort", distance: "15 km" },
      { name: "Jaigarh Fort", distance: "12 km" },
      { name: "Albert Hall Museum", distance: "5 km" },
      { name: "Jal Mahal", distance: "6 km" },
      { name: "Birla Mandir", distance: "8 km" },
      { name: "Galtaji Temple", distance: "10 km" },
      { name: "Govind Dev Ji Temple", distance: "4 km" },
      { name: "Sisodia Rani Garden", distance: "9 km" },
    ],
    howToReach: "Jaipur Int'l Airport, Jaipur Railway Station, NH 8 from Delhi 280 km",
    tips: ["Bargain at markets", "Visit Sunday for palace illumination", "Hire audio guide"],
    contactNumber: "+91-141-2221111",
    website: "https://tourism.rajasthan.gov.in",
    trending: true,
    trendingRank: 2,
    popularity: 95,
  },

  {
    name: "Goa Beaches",
    category: "Beach",
    description:
      "Goa, India's smallest state, is renowned for pristine beaches, vibrant nightlife, Portuguese heritage, and laid-back atmosphere. Perfect blend of Indian and Portuguese cultures.",
    location: {
      city: "Goa",
      state: "Goa",
      country: "India",
      coordinates: { lat: 15.2993, lng: 74.124 },
      address: "Goa, India",
    },
    rating: 4.8,
    reviews: 156000,
    entryFee: "Beaches free, Water sports ₹500-3000",
    timings: "24/7 (Beaches), Clubs 9 PM - 4 AM",
    bestTimeToVisit: "November to February",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800",
    highlights: [
      "Baga Beach nightlife",
      "Calangute Beach",
      "Palolem Beach",
      "Basilica of Bom Jesus",
      "Fort Aguada",
      "Dudhsagar Falls",
    ],
    activities: [
      "Parasailing",
      "Scuba diving",
      "Dolphin watching",
      "Beach parties",
      "Casino cruises",
      "Spice plantation tours",
    ],
    nearbyAttractions: [
      { name: "Calangute Beach", distance: "15 km" },
      { name: "Fort Aguada", distance: "18 km" },
      { name: "Dudhsagar Falls", distance: "60 km" },
      { name: "Basilica of Bom Jesus", distance: "10 km" },
      { name: "Anjuna Beach", distance: "20 km" },
      { name: "Chapora Fort", distance: "22 km" },
      { name: "Se Cathedral", distance: "10 km" },
      { name: "Reis Magos Fort", distance: "12 km" },
      { name: "Vagator Beach", distance: "21 km" },
      { name: "Dr. Salim Ali Bird Sanctuary", distance: "8 km" },
    ],
    howToReach: "Goa Airport Dabolim 30 km, Madgaon Station, NH 66 from Mumbai 580 km",
    tips: [
      "Rent scooter for mobility",
      "Book Dec-Jan in advance",
      "Respect beach rules",
      "Try authentic Goan food",
    ],
    contactNumber: "+91-832-2438750",
    website: "https://www.goatourism.gov.in",
    trending: true,
    trendingRank: 3,
    popularity: 98,
  },

  {
    name: "Varanasi (Kashi)",
    category: "Religious",
    description:
      "Varanasi, one of the oldest cities in the world (3000+ years), is the spiritual capital of India. Famous for ghats, temples, Ganga Aarti, and as a center of learning and culture.",
    location: {
      city: "Varanasi",
      state: "Uttar Pradesh",
      country: "India",
      coordinates: { lat: 25.3176, lng: 82.9739 },
      address: "Varanasi, Uttar Pradesh, India",
    },
    rating: 4.7,
    reviews: 87000,
    entryFee: "Ghats free, Boat ride ₹150-300",
    timings: "24/7 (Ghats)",
    bestTimeToVisit: "October to March",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800",
    highlights: [
      "Dashashwamedh Ghat Aarti",
      "Kashi Vishwanath Temple",
      "Assi Ghat",
      "Sarnath",
      "BHU",
      "Ramnagar Fort",
    ],
    activities: [
      "Sunrise boat ride",
      "Evening Ganga Aarti",
      "Heritage walks",
      "Silk shopping",
      "Classical music concerts",
    ],
    nearbyAttractions: [
      { name: "Sarnath", distance: "10 km" },
      { name: "Dasaswamedh Ghat", distance: "1 km" },
      { name: "Assi Ghat", distance: "2 km" },
      { name: "Ramnagar Fort", distance: "14 km" },
      { name: "Manikarnika Ghat", distance: "1.5 km" },
      { name: "Bharat Mata Mandir", distance: "3 km" },
      { name: "Tulsi Manas Mandir", distance: "4 km" },
      { name: "Sankat Mochan Hanuman Temple", distance: "5 km" },
      { name: "New Vishwanath Temple (BHU)", distance: "6 km" },
      { name: "Alamgir Mosque", distance: "2 km" },
    ],
    howToReach: "Lal Bahadur Shastri Airport 25 km, Varanasi Junction Station",
    tips: [
      "Dress modestly",
      "Bargain for boat rides",
      "Respect cremation ceremonies",
      "Carry cash",
    ],
    contactNumber: "+91-542-2506670",
    website: "https://www.varanasi.nic.in",
    trending: true,
    trendingRank: 4,
    popularity: 92,
  },

  {
    name: "Kerala Backwaters",
    category: "Natural Wonder",
    description:
      "A network of 900+ km of interconnected canals, rivers, lakes, and inlets along Kerala's coast. Famous for houseboats, lush greenery, and serene village life.",
    location: {
      city: "Alleppey (Alappuzha)",
      state: "Kerala",
      country: "India",
      coordinates: { lat: 9.4981, lng: 76.3388 },
      address: "Alleppey, Kerala, India",
    },
    rating: 4.8,
    reviews: 94000,
    entryFee: "Houseboat ₹8,000-25,000",
    timings: "Check-in 12 PM, Check-out 9 AM",
    bestTimeToVisit: "November to February",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800",
    highlights: [
      "Houseboat stays",
      "Vembanad Lake",
      "Kumarakom Bird Sanctuary",
      "Nehru Trophy Boat Race",
      "Traditional villages",
    ],
    activities: [
      "Houseboat cruise",
      "Canoeing",
      "Village walks",
      "Ayurvedic treatments",
      "Bird watching",
      "Fishing",
    ],
    nearbyAttractions: [
      { name: "Alleppey Beach", distance: "2 km" },
      { name: "Marari Beach", distance: "15 km" },
      { name: "Krishnapuram Palace", distance: "47 km" },
      { name: "Pathiramanal Island", distance: "13 km" },
      { name: "Ambalapuzha Temple", distance: "14 km" },
      { name: "Vembanad Lake", distance: "5 km" },
      { name: "Kuttanad", distance: "20 km" },
      { name: "St. Mary's Forane Church", distance: "10 km" },
      { name: "Revi Karunakaran Museum", distance: "3 km" },
      { name: "Punnamada Lake", distance: "4 km" },
    ],
    howToReach: "Cochin Airport 85 km, Alleppey Station, NH 66",
    tips: [
      "Book houseboats in advance",
      "Carry mosquito repellent",
      "Try Karimeen fish",
      "Respect village customs",
    ],
    contactNumber: "+91-477-2253308",
    website: "https://www.keralatourism.org",
    trending: true,
    trendingRank: 5,
    popularity: 93,
  },

  {
    name: "Ladakh - Land of High Passes",
    category: "Adventure",
    description:
      "High-altitude desert with stunning landscapes, Buddhist monasteries, adventurous roads, and pristine lakes. Features world's highest motorable passes and unique Tibetan Buddhist culture.",
    location: {
      city: "Leh",
      state: "Ladakh",
      country: "India",
      coordinates: { lat: 34.1526, lng: 77.5771 },
      address: "Leh, Ladakh, India",
    },
    rating: 4.9,
    reviews: 112000,
    entryFee: "Permits ₹400-800, Monasteries ₹50-100",
    timings: "Weather dependent",
    bestTimeToVisit: "May to September",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    highlights: [
      "Pangong Lake",
      "Nubra Valley",
      "Khardung La Pass",
      "Magnetic Hill",
      "Thiksey Monastery",
      "Hemis Monastery",
      "Shanti Stupa",
    ],
    activities: [
      "Motorcycle tours",
      "River rafting",
      "Trekking",
      "Camping",
      "Stargazing",
      "Monastery visits",
    ],
    nearbyAttractions: [
      { name: "Pangong Lake", distance: "160 km" },
      { name: "Nubra Valley", distance: "120 km" },
      { name: "Thiksey Monastery", distance: "19 km" },
      { name: "Magnetic Hill", distance: "30 km" },
      { name: "Shanti Stupa", distance: "5 km" },
      { name: "Leh Palace", distance: "2 km" },
      { name: "Spituk Gompa", distance: "8 km" },
      { name: "Hemis National Park", distance: "50 km" },
      { name: "Gurudwara Pathar Sahib", distance: "25 km" },
      { name: "Hall of Fame", distance: "6 km" },
    ],
    howToReach: "Leh Airport (best), Manali-Leh Highway 475 km, Srinagar-Leh 420 km",
    tips: [
      "Acclimatize 2-3 days",
      "Get Inner Line Permits",
      "Carry AMS medicines",
      "Pack warm clothes",
      "Carry cash",
    ],
    contactNumber: "+91-1982-252297",
    website: "https://www.ladakh.nic.in",
    trending: true,
    trendingRank: 6,
    popularity: 96,
  },

  {
    name: "Rishikesh - Yoga Capital",
    category: "Adventure",
    description:
      "Spiritual town in Himalayan foothills on Ganges River, known as Yoga Capital of the World. Famous for temples, ashrams, adventure sports, and Beatles Ashram.",
    location: {
      city: "Rishikesh",
      state: "Uttarakhand",
      country: "India",
      coordinates: { lat: 30.0869, lng: 78.2676 },
      address: "Rishikesh, Uttarakhand, India",
    },
    rating: 4.7,
    reviews: 78000,
    entryFee: "Temples free, Rafting ₹500-2500, Bungee ₹3500",
    timings: "Temples 5 AM - 9 PM",
    bestTimeToVisit: "September to November, March to May",
    image: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800",
    highlights: [
      "Lakshman Jhula",
      "Ram Jhula",
      "Triveni Ghat Aarti",
      "Beatles Ashram",
      "Parmarth Niketan",
      "Adventure sports",
    ],
    activities: [
      "White water rafting",
      "Bungee jumping",
      "Yoga retreats",
      "River camping",
      "Trekking",
      "Cafe hopping",
    ],
    nearbyAttractions: [
      { name: "Lakshman Jhula", distance: "2 km" },
      { name: "Ram Jhula", distance: "3 km" },
      { name: "Triveni Ghat", distance: "5 km" },
      { name: "Neer Garh Waterfall", distance: "8 km" },
      { name: "Beatles Ashram", distance: "4 km" },
      { name: "Parmarth Niketan", distance: "3.5 km" },
      { name: "Vashishta Gufa", distance: "22 km" },
      { name: "Kunjapuri Devi Temple", distance: "25 km" },
      { name: "Rajaji National Park", distance: "18 km" },
      { name: "Shivpuri", distance: "16 km" },
    ],
    howToReach: "Jolly Grant Airport Dehradun 35 km, Haridwar Station 25 km, Delhi 240 km",
    tips: [
      "Alcohol/meat free zone",
      "Book rafting from certified operators",
      "Wear modest clothes",
      "Carry ID for activities",
    ],
    contactNumber: "+91-135-2430209",
    website: "https://uttarakhandtourism.gov.in",
    trending: true,
    trendingRank: 7,
    popularity: 89,
  },

  {
    name: "Darjeeling - Queen of Hills",
    category: "Hill Station",
    description:
      "Picturesque hill station famous for tea plantations, Kanchenjunga views, colonial architecture, and UNESCO Heritage Toy Train. Blend of Nepali, Tibetan, and British cultures.",
    location: {
      city: "Darjeeling",
      state: "West Bengal",
      country: "India",
      coordinates: { lat: 27.041, lng: 88.2663 },
      address: "Darjeeling, West Bengal, India",
    },
    rating: 4.6,
    reviews: 72000,
    entryFee: "Toy Train ₹1,390 Joy Ride, Zoo ₹50",
    timings: "Sunrise point 4 AM, Attractions 8 AM - 5 PM",
    bestTimeToVisit: "March to May, October to December",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800",
    highlights: [
      "Tiger Hill sunrise",
      "Toy Train",
      "Tea gardens",
      "Batasia Loop",
      "Peace Pagoda",
      "Himalayan Zoo",
      "Happy Valley Estate",
    ],
    activities: [
      "Toy train ride",
      "Tea tasting",
      "Sunrise viewing",
      "Cable car ride",
      "Monastery visits",
      "Shopping",
    ],
    nearbyAttractions: [
      { name: "Tiger Hill", distance: "11 km" },
      { name: "Batasia Loop", distance: "5 km" },
      { name: "Ghoom Monastery", distance: "8 km" },
      { name: "Peace Pagoda", distance: "2 km" },
      { name: "Rock Garden", distance: "4 km" },
      { name: "Himalayan Mountaineering Institute", distance: "3 km" },
      { name: "Padmaja Naidu Himalayan Zoological Park", distance: "3 km" },
      { name: "Happy Valley Tea Estate", distance: "3 km" },
      { name: "Observatory Hill", distance: "1 km" },
      { name: "Mahakal Temple", distance: "1.5 km" },
    ],
    howToReach: "Bagdogra Airport 95 km, New Jalpaiguri Station 70 km, Siliguri 70 km",
    tips: [
      "Book toy train advance",
      "Tiger Hill needs 3:30 AM start",
      "Carry warm clothes",
      "Try fresh Darjeeling tea",
    ],
    contactNumber: "+91-354-2254102",
    website: "https://darjeelingtourism.gov.in",
    trending: true,
    trendingRank: 8,
    popularity: 87,
  },

  {
    name: "Andaman Islands",
    category: "Beach",
    description:
      "Tropical islands with pristine beaches, turquoise waters, coral reefs, and rich marine life. Famous for water sports, scuba diving, and historical Cellular Jail.",
    location: {
      city: "Port Blair",
      state: "Andaman and Nicobar Islands",
      country: "India",
      coordinates: { lat: 11.6234, lng: 92.7265 },
      address: "Port Blair, Andaman, India",
    },
    rating: 4.8,
    reviews: 85000,
    entryFee: "Beaches free, Scuba ₹3,500-5,500",
    timings: "Beaches open all day",
    bestTimeToVisit: "October to May",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    highlights: [
      "Radhanagar Beach",
      "Cellular Jail",
      "Ross Island",
      "Neil Island",
      "Elephant Beach",
      "North Bay",
      "Baratang Caves",
    ],
    activities: [
      "Scuba diving",
      "Snorkeling",
      "Sea walking",
      "Parasailing",
      "Island hopping",
      "Glass bottom boat",
      "Beach camping",
    ],
    nearbyAttractions: [
      { name: "Havelock Island", distance: "50 km" },
      { name: "Neil Island", distance: "40 km" },
      { name: "Ross Island", distance: "3 km" },
      { name: "Baratang Island", distance: "100 km" },
      { name: "Chidiya Tapu", distance: "25 km" },
      { name: "North Bay Island", distance: "5 km" },
      { name: "Wandoor Beach", distance: "25 km" },
      { name: "Mahatma Gandhi Marine National Park", distance: "25 km" },
      { name: "Mount Harriet National Park", distance: "45 km" },
      { name: "Corbyn's Cove Beach", distance: "7 km" },
    ],
    howToReach: "Port Blair Airport, Ships from Kolkata/Chennai (3-4 days)",
    tips: [
      "Book ferries advance",
      "Carry cash",
      "Use reef-safe sunscreen",
      "Get RAP for foreigners",
    ],
    contactNumber: "+91-3192-233006",
    website: "https://www.andamans.gov.in",
    trending: true,
    trendingRank: 9,
    popularity: 91,
  },

  {
    name: "Mysore Palace",
    category: "Historical",
    description:
      "Magnificent Indo-Saracenic palace, one of India's most visited monuments. Features grand arches, ornate halls, and illuminated with 100,000 bulbs on Sundays.",
    location: {
      city: "Mysore",
      state: "Karnataka",
      country: "India",
      coordinates: { lat: 12.3052, lng: 76.6551 },
      address: "Sayyaji Rao Road, Mysuru, Karnataka 570001",
    },
    rating: 4.7,
    reviews: 95000,
    entryFee: "₹70 Indians, ₹200 Foreigners",
    timings: "10 AM - 5:30 PM, Illumination Sundays 7-8 PM",
    bestTimeToVisit: "October to February, Dasara Festival",
    image: "https://images.unsplash.com/photo-1609416917477-fde942239fbf?w=800",
    highlights: [
      "Indo-Saracenic architecture",
      "Durbar Hall",
      "Golden Howdah",
      "Sunday illumination",
      "Dasara celebrations",
      "Royal museum",
    ],
    activities: [
      "Guided tours",
      "Dasara procession",
      "Photography (exterior)",
      "Palace grounds walks",
    ],
    nearbyAttractions: [
      { name: "Brindavan Gardens", distance: "20 km" },
      { name: "Chamundi Hill", distance: "13 km" },
      { name: "St. Philomena's Church", distance: "3 km" },
      { name: "Mysore Zoo", distance: "2 km" },
      { name: "Jaganmohan Palace", distance: "1.5 km" },
      { name: "Karanji Lake", distance: "3 km" },
      { name: "Rail Museum", distance: "2 km" },
      { name: "Lalitha Mahal", distance: "5 km" },
      { name: "Ranganathittu Bird Sanctuary", distance: "16 km" },
      { name: "Srirangapatna", distance: "15 km" },
    ],
    howToReach: "Mysore Airport 10 km, Bangalore Airport 170 km, Mysore Station 2 km",
    tips: [
      "No photography inside",
      "Remove footwear",
      "Visit Sunday evening for lights",
      "Attend Dasara festival",
    ],
    contactNumber: "+91-821-2421051",
    website: "https://mysorepalace.gov.in",
    trending: true,
    trendingRank: 10,
    popularity: 88,
  },

  {
    name: "Hampi",
    category: "Historical",
    description:
      "UNESCO World Heritage Site with ruins of Vijayanagara Empire. Ancient temples, massive boulders, and stunning landscapes create a surreal archaeological wonder.",
    location: {
      city: "Hampi",
      state: "Karnataka",
      country: "India",
      coordinates: { lat: 15.335, lng: 76.46 },
      address: "Hampi, Karnataka, India",
    },
    rating: 4.7,
    reviews: 68000,
    entryFee: "₹40 Indians, ₹600 Foreigners",
    timings: "6 AM - 6 PM",
    bestTimeToVisit: "October to February",
    image: "https://images.unsplash.com/photo-1588416936097-41850ab3d86d?w=800",
    highlights: [
      "Virupaksha Temple",
      "Stone Chariot",
      "Vittala Temple",
      "Elephant Stables",
      "Lotus Mahal",
      "Matanga Hill sunrise",
    ],
    activities: [
      "Temple exploration",
      "Rock climbing",
      "Coracle rides",
      "Cycling tours",
      "Sunrise/sunset viewing",
    ],
    nearbyAttractions: [
      { name: "Virupaksha Temple", distance: "0.5 km" },
      { name: "Vittala Temple", distance: "2 km" },
      { name: "Lotus Mahal", distance: "3 km" },
      { name: "Elephant Stables", distance: "3.2 km" },
      { name: "Matanga Hill", distance: "1 km" },
      { name: "Hemakuta Hill Temple", distance: "0.8 km" },
      { name: "Achyutaraya Temple", distance: "1.5 km" },
      { name: "Hazara Rama Temple", distance: "2.5 km" },
      { name: "Queen's Bath", distance: "3.5 km" },
      { name: "Tungabhadra Dam", distance: "15 km" },
    ],
    howToReach: "Hubli Airport 160 km, Hospet Station 13 km, Bangalore 350 km",
    tips: [
      "Rent bicycle/scooter",
      "Wear comfortable shoes",
      "Carry water",
      "Climb Matanga Hill for sunset",
    ],
    contactNumber: "+91-8394-241339",
    website: "https://karnatakatourism.org",
    trending: true,
    trendingRank: 11,
    popularity: 85,
  },

  {
    name: "Udaipur - City of Lakes",
    category: "Historical",
    description:
      "Romantic city with beautiful palaces, lakes, and havelis. Known as Venice of the East, famous for City Palace, Lake Pichola, and Rajasthani culture.",
    location: {
      city: "Udaipur",
      state: "Rajasthan",
      country: "India",
      coordinates: { lat: 24.5854, lng: 73.7125 },
      address: "Udaipur, Rajasthan, India",
    },
    rating: 4.7,
    reviews: 82000,
    entryFee: "₹300 City Palace, ₹700 Lake Palace view",
    timings: "9:30 AM - 5:30 PM",
    bestTimeToVisit: "September to March",
    image: "https://images.unsplash.com/photo-1580055733199-07e48814c6dc?w=800",
    highlights: [
      "City Palace",
      "Lake Pichola",
      "Jag Mandir",
      "Jag Niwas (Lake Palace Hotel)",
      "Saheliyon Ki Bari",
      "Bagore Ki Haveli",
    ],
    activities: [
      "Boat rides",
      "Palace tours",
      "Cultural shows",
      "Shopping",
      "Rooftop dining",
      "Heritage walks",
    ],
    nearbyAttractions: [
      { name: "Lake Pichola", distance: "1 km" },
      { name: "Jag Mandir", distance: "1.5 km" },
      { name: "Saheliyon Ki Bari", distance: "4 km" },
      { name: "Fateh Sagar Lake", distance: "5 km" },
      { name: "Sajjangarh Monsoon Palace", distance: "10 km" },
      { name: "Bagore Ki Haveli", distance: "0.5 km" },
      { name: "Jagdish Temple", distance: "0.2 km" },
      { name: "Shilpgram", distance: "6 km" },
      { name: "Vintage Car Museum", distance: "2 km" },
      { name: "Eklingji Temple", distance: "22 km" },
    ],
    howToReach: "Maharana Pratap Airport 22 km, Udaipur City Station, NH 8",
    tips: [
      "Book lake view hotels",
      "Take sunset boat ride",
      "Attend cultural show at Bagore Ki Haveli",
      "Walk old city lanes",
    ],
    contactNumber: "+91-294-2411535",
    website: "https://tourism.rajasthan.gov.in",
    trending: true,
    trendingRank: 12,
    popularity: 86,
  },

  {
    name: "Munnar",
    category: "Hill Station",
    description:
      "Picturesque hill station in Western Ghats, famous for tea plantations, misty mountains, and pleasant climate. Ideal for nature lovers and honeymooners.",
    location: {
      city: "Munnar",
      state: "Kerala",
      country: "India",
      coordinates: { lat: 10.0889, lng: 77.0595 },
      address: "Munnar, Kerala, India",
    },
    rating: 4.6,
    reviews: 71000,
    entryFee: "Tea museum ₹125, National Park ₹360",
    timings: "Tea estates 8 AM - 5 PM",
    bestTimeToVisit: "September to March",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800",
    highlights: [
      "Tea plantations",
      "Anamudi Peak",
      "Mattupetty Dam",
      "Echo Point",
      "Eravikulam National Park",
      "Tea Museum",
    ],
    activities: [
      "Tea estate tours",
      "Trekking",
      "Boating",
      "Wildlife spotting",
      "Photography",
      "Cycling",
    ],
    nearbyAttractions: [
      { name: "Orchid Park", distance: "5 km" },
      { name: "Tea Gardens", distance: "10 km" },
      { name: "Kakochang Waterfalls", distance: "15 km" },
      { name: "Deopahar Ruins", distance: "45 km" },
      { name: "Hollongapar Gibbon Sanctuary", distance: "80 km" },
      { name: "Addabarie Tea Estate", distance: "20 km" },
      { name: "Majuli Island", distance: "100 km" },
      { name: "Nameri National Park", distance: "90 km" },
      { name: "Tezpur", distance: "50 km" },
      { name: "Bura-Chapori Wildlife Sanctuary", distance: "40 km" },
    ],
    howToReach: "Cochin Airport 110 km, Aluva Station 110 km, Madurai 140 km",
    tips: [
      "Carry warm clothes",
      "Try fresh tea",
      "Book Neelakurinji season (once in 12 years)",
      "Hire local taxi",
    ],
    contactNumber: "+91-4865-231516",
    website: "https://www.keralatourism.org",
    trending: true,
    trendingRank: 13,
    popularity: 84,
  },

  {
    name: "Coorg",
    category: "Hill Station",
    description:
      "Scotland of India, known for coffee plantations, lush green hills, waterfalls, and Kodava culture. Perfect for nature walks and plantation stays.",
    location: {
      city: "Coorg (Kodagu)",
      state: "Karnataka",
      country: "India",
      coordinates: { lat: 12.3375, lng: 75.8069 },
      address: "Coorg, Karnataka, India",
    },
    rating: 4.6,
    reviews: 65000,
    entryFee: "Abbey Falls ₹15, Dubare Camp ₹300",
    timings: "Daylight hours for outdoor activities",
    bestTimeToVisit: "October to March",
    image: "https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=800",
    highlights: [
      "Coffee plantations",
      "Abbey Falls",
      "Raja's Seat",
      "Dubare Elephant Camp",
      "Talakaveri",
      "Nagarhole National Park",
    ],
    activities: [
      "Plantation tours",
      "Trekking",
      "River rafting",
      "Elephant interaction",
      "Bird watching",
      "Coffee tasting",
    ],
    nearbyAttractions: [
      { name: "Abbey Falls", distance: "8 km" },
      { name: "Raja's Seat", distance: "1 km" },
      { name: "Dubare Elephant Camp", distance: "30 km" },
      { name: "Talakaveri", distance: "45 km" },
      { name: "Golden Temple (Bylakuppe)", distance: "35 km" },
      { name: "Omkareshwara Temple", distance: "1 km" },
      { name: "Mandalpatti", distance: "20 km" },
      { name: "Nisargadhama", distance: "28 km" },
      { name: "Iruppu Falls", distance: "75 km" },
      { name: "Brahmagiri Wildlife Sanctuary", distance: "60 km" },
    ],
    howToReach: "Mangalore Airport 160 km, Mysore Station 120 km, Bangalore 260 km",
    tips: [
      "Stay in homestays",
      "Try Pandi Curry",
      "Buy fresh coffee",
      "Monsoon offers lush beauty",
    ],
    contactNumber: "+91-8272-228580",
    website: "https://karnatakatourism.org",
    trending: true,
    trendingRank: 14,
    popularity: 83,
  },

  {
    name: "Shimla",
    category: "Hill Station",
    description:
      "Former summer capital of British India, famous for colonial architecture, Mall Road, toy train, and pleasant climate. Popular honeymoon destination.",
    location: {
      city: "Shimla",
      state: "Himachal Pradesh",
      country: "India",
      coordinates: { lat: 31.1048, lng: 77.1734 },
      address: "Shimla, Himachal Pradesh, India",
    },
    rating: 4.5,
    reviews: 79000,
    entryFee: "Most attractions free, Museum ₹50",
    timings: "Mall Road all day, Museums 10 AM - 5 PM",
    bestTimeToVisit: "March to June (Summer), December to February (Snow)",
    image: "https://images.unsplash.com/photo-1566837945700-30057527ade0?w=800",
    highlights: [
      "Mall Road",
      "The Ridge",
      "Christ Church",
      "Viceregal Lodge",
      "Jakhoo Temple",
      "Toy Train",
      "Kufri",
    ],
    activities: [
      "Shopping on Mall Road",
      "Toy train ride",
      "Trekking",
      "Ice skating (winter)",
      "Horse riding",
      "Photography",
    ],
    nearbyAttractions: [
      { name: "Kufri", distance: "15 km" },
      { name: "Jakhu Temple", distance: "2 km" },
      { name: "Christ Church", distance: "0.5 km" },
      { name: "Mall Road", distance: "0 km" },
      { name: "Summer Hill", distance: "5 km" },
      { name: "Chadwick Falls", distance: "7 km" },
      { name: "Tara Devi Temple", distance: "11 km" },
      { name: "Annandale", distance: "3 km" },
      { name: "Viceregal Lodge", distance: "3 km" },
      { name: "Mashobra", distance: "10 km" },
    ],
    howToReach: "Chandigarh Airport 115 km, Kalka Station (toy train), NH 5 from Chandigarh",
    tips: [
      "Book hotels advance in season",
      "Toy train Kalka-Shimla is scenic",
      "Carry woolens",
      "Walk Mall Road",
    ],
    contactNumber: "+91-177-2652561",
    website: "https://himachaltourism.gov.in",
    trending: true,
    trendingRank: 15,
    popularity: 82,
  },

  {
    name: "Manali",
    category: "Hill Station",
    description:
      "Popular hill station at the northern end of Kullu Valley, gateway to Rohtang Pass and Lahaul-Spiti. Famous for adventure sports, scenic beauty, and backpacker culture.",
    location: {
      city: "Manali",
      state: "Himachal Pradesh",
      country: "India",
      coordinates: { lat: 32.2432, lng: 77.1892 },
      address: "Manali, Himachal Pradesh, India",
    },
    rating: 4.6,
    reviews: 91000,
    entryFee: "Rohtang Pass permit ₹500, Activities vary",
    timings: "Open all day, Rohtang 7 AM - 4 PM (May-Oct)",
    bestTimeToVisit: "October to February (Snow), May to June (Summer)",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800",
    highlights: [
      "Rohtang Pass",
      "Solang Valley",
      "Hadimba Temple",
      "Old Manali",
      "Vashisht Hot Springs",
      "Manu Temple",
      "Beas River",
    ],
    activities: [
      "Skiing",
      "Paragliding",
      "River rafting",
      "Trekking",
      "Cable car",
      "Zorbing",
      "Mountain biking",
    ],
    nearbyAttractions: [
      { name: "Solang Valley", distance: "14 km" },
      { name: "Rohtang Pass", distance: "51 km" },
      { name: "Hidimba Devi Temple", distance: "2 km" },
      { name: "Vashisht Hot Water Springs", distance: "3 km" },
      { name: "Old Manali", distance: "2 km" },
      { name: "Jogini Waterfalls", distance: "4 km" },
      { name: "Manu Temple", distance: "2.5 km" },
      { name: "Naggar Castle", distance: "20 km" },
      { name: "Bhrigu Lake", distance: "18 km" },
      { name: "Beas River", distance: "1 km" },
    ],
    howToReach: "Bhuntar Airport 50 km, Chandigarh 310 km, Delhi 540 km by road",
    tips: [
      "Get Rohtang permit online",
      "Stay in Old Manali for cafes",
      "Carry warm clothes",
      "Try local trout fish",
    ],
    contactNumber: "+91-1902-252116",
    website: "https://himachaltourism.gov.in",
    trending: true,
    trendingRank: 16,
    popularity: 90,
  },

  {
    name: "Amritsar - Golden Temple",
    category: "Religious",
    description:
      "Spiritual center of Sikhism, home to the iconic Golden Temple (Harmandir Sahib). Rich in history, culture, and close to Wagah Border for the Beating Retreat ceremony.",
    location: {
      city: "Amritsar",
      state: "Punjab",
      country: "India",
      coordinates: { lat: 31.634, lng: 74.8723 },
      address: "Amritsar, Punjab, India",
    },
    rating: 4.9,
    reviews: 105000,
    entryFee: "Free (Golden Temple), Wagah ₹0",
    timings: "Golden Temple 24/7, Wagah ceremony 4:15 PM",
    bestTimeToVisit: "November to March",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800",
    highlights: [
      "Golden Temple",
      "Jallianwala Bagh",
      "Wagah Border ceremony",
      "Akal Takht",
      "Durgiana Temple",
      "Partition Museum",
    ],
    activities: [
      "Langar (community meal)",
      "Night viewing of temple",
      "Wagah Border ceremony",
      "Heritage walks",
      "Shopping",
    ],
    nearbyAttractions: [
      { name: "Wagah Border", distance: "30 km" },
      { name: "Jallianwala Bagh", distance: "0.5 km" },
      { name: "Partition Museum", distance: "1 km" },
      { name: "Gobindgarh Fort", distance: "2 km" },
      { name: "Durgiana Temple", distance: "1.5 km" },
      { name: "Ram Tirth", distance: "11 km" },
      { name: "Akal Takht", distance: "0.1 km" },
      { name: "Maharaja Ranjit Singh Museum", distance: "3 km" },
      { name: "Mata Lal Devi Temple", distance: "2 km" },
      { name: "Khair-ud-Din Masjid", distance: "1.5 km" },
    ],
    howToReach: "Amritsar Airport 11 km, Amritsar Junction Station, NH 1 from Delhi 450 km",
    tips: [
      "Cover head at temple",
      "Experience langar",
      "Reach Wagah early for seats",
      "Try Amritsari kulcha",
      "Visit at night for serene view",
    ],
    contactNumber: "+91-183-2401000",
    website: "https://www.goldentempleamritsar.org",
    trending: true,
    trendingRank: 17,
    popularity: 94,
  },

  {
    name: "Khajuraho Temples",
    category: "Historical",
    description:
      "UNESCO World Heritage Site famous for stunning temples with intricate erotic sculptures. Masterpiece of Chandela dynasty showcasing medieval Indian architecture.",
    location: {
      city: "Khajuraho",
      state: "Madhya Pradesh",
      country: "India",
      coordinates: { lat: 24.8318, lng: 79.9199 },
      address: "Khajuraho, Madhya Pradesh, India",
    },
    rating: 4.6,
    reviews: 48000,
    entryFee: "₹40 Indians, ₹600 Foreigners",
    timings: "Sunrise to Sunset, Light Show 7 PM",
    bestTimeToVisit: "October to February",
    image: "https://images.unsplash.com/photo-1609416917477-fde942239fbf?w=800",
    highlights: [
      "Kandariya Mahadev Temple",
      "Lakshmana Temple",
      "Vishwanath Temple",
      "Erotic sculptures",
      "Light and sound show",
    ],
    activities: [
      "Temple exploration",
      "Light show",
      "Archaeological museum visit",
      "Photography",
      "Cultural performances",
    ],
    nearbyAttractions: [
      { name: "Western Group of Temples", distance: "1 km" },
      { name: "Eastern Group of Temples", distance: "2 km" },
      { name: "Raneh Falls", distance: "20 km" },
      { name: "Panna National Park", distance: "25 km" },
      { name: "Pandav Falls", distance: "30 km" },
      { name: "Archaeological Museum", distance: "1 km" },
      { name: "Jain Temples", distance: "2 km" },
      { name: "Dulhadev Temple", distance: "3 km" },
      { name: "Chaturbhuj Temple", distance: "4 km" },
      { name: "Ken Gharial Sanctuary", distance: "25 km" },
    ],
    howToReach: "Khajuraho Airport well connected, Khajuraho Station, Jhansi 175 km",
    tips: [
      "Hire guide for history",
      "Attend light show",
      "Western group has main temples",
      "Visit early to avoid heat",
    ],
    contactNumber: "+91-7686-272047",
    website: "https://www.mptourism.com",
    trending: true,
    trendingRank: 18,
    popularity: 79,
  },

  {
    name: "Ajanta & Ellora Caves",
    category: "Historical",
    description:
      "UNESCO World Heritage Sites with ancient rock-cut caves. Ajanta has Buddhist frescoes, Ellora features Hindu, Buddhist, and Jain temples carved from rock.",
    location: {
      city: "Aurangabad",
      state: "Maharashtra",
      country: "India",
      coordinates: { lat: 20.5522, lng: 75.7033 },
      address: "Near Aurangabad, Maharashtra, India",
    },
    rating: 4.7,
    reviews: 52000,
    entryFee: "₹40 Indians, ₹600 Foreigners per site",
    timings: "9 AM - 5:30 PM (Closed Mondays for Ajanta, Tuesdays for Ellora)",
    bestTimeToVisit: "October to March",
    image: "https://images.unsplash.com/photo-1609416917477-fde942239fbf?w=800",
    highlights: [
      "Kailasa Temple (Ellora)",
      "Buddhist caves with frescoes (Ajanta)",
      "Rock-cut architecture",
      "Ancient paintings",
      "Multi-faith caves",
    ],
    activities: ["Cave exploration", "Photography", "Historical tours", "Museum visits"],
    nearbyAttractions: [
      { name: "Ellora Caves", distance: "100 km" },
      { name: "Bibi Ka Maqbara", distance: "105 km" },
      { name: "Daulatabad Fort", distance: "110 km" },
      { name: "Grishneshwar Temple", distance: "100 km" },
      { name: "Aurangabad Caves", distance: "105 km" },
      { name: "Panchakki", distance: "104 km" },
      { name: "Siddharth Garden", distance: "103 km" },
      { name: "Bhadra Maruti Temple", distance: "108 km" },
      { name: "Jayakwadi Dam", distance: "140 km" },
      { name: "Gautala Autramghat Sanctuary", distance: "120 km" },
    ],
    howToReach: "Aurangabad Airport 30 km, Aurangabad Station, Ajanta 100 km, Ellora 30 km",
    tips: [
      "Visit both caves separate days",
      "Hire guide for history",
      "Carry water",
      "Wear comfortable shoes",
      "Photography restricted in some caves",
    ],
    contactNumber: "+91-240-2331513",
    website: "https://www.maharashtratourism.gov.in",
    trending: true,
    trendingRank: 19,
    popularity: 81,
  },

  {
    name: "Kaziranga National Park",
    category: "Wildlife",
    description:
      "UNESCO World Heritage Site and home to two-thirds of world's one-horned rhinoceroses. Rich biodiversity with elephants, tigers, wild buffalo, and diverse birdlife.",
    location: {
      city: "Kaziranga",
      state: "Assam",
      country: "India",
      coordinates: { lat: 26.5775, lng: 93.1711 },
      address: "Kaziranga, Assam, India",
    },
    rating: 4.7,
    reviews: 38000,
    entryFee: "Indians ₹150, Foreigners ₹1750, Safari ₹1050-2450",
    timings: "Safaris 7 AM & 1:30 PM (Nov-April)",
    bestTimeToVisit: "November to April",
    image: "https://images.unsplash.com/photo-1564760055775-d63b17a55c44?w=800",
    highlights: [
      "One-horned rhinoceros",
      "Bengal tigers",
      "Wild elephants",
      "Swamp deer",
      "Bird watching",
      "Elephant safari",
      "Jeep safari",
    ],
    activities: [
      "Elephant safari",
      "Jeep safari",
      "Bird watching",
      "Nature photography",
      "River cruise",
    ],
    nearbyAttractions: [
      { name: "Orchid Park", distance: "5 km" },
      { name: "Tea Gardens", distance: "10 km" },
      { name: "Kakochang Waterfalls", distance: "15 km" },
      { name: "Deopahar Ruins", distance: "45 km" },
      { name: "Hollongapar Gibbon Sanctuary", distance: "80 km" },
      { name: "Addabarie Tea Estate", distance: "20 km" },
      { name: "Majuli Island", distance: "100 km" },
      { name: "Nameri National Park", distance: "90 km" },
      { name: "Tezpur", distance: "50 km" },
      { name: "Bura-Chapori Wildlife Sanctuary", distance: "40 km" },
    ],
    howToReach: "Jorhat Airport 97 km, Furkating Station 75 km, Guwahati 217 km",
    tips: [
      "Book safari advance",
      "Carry binoculars",
      "Wear muted colors",
      "Park closed July-October (monsoon)",
      "Stay in Kohora",
    ],
    contactNumber: "+91-3776-268095",
    website: "https://www.kaziranga-national-park.com",
    trending: true,
    trendingRank: 20,
    popularity: 77,
  },

  {
    name: "Ooty - Queen of Hill Stations",
    category: "Hill Station",
    description:
      "Popular hill station in Nilgiri Hills, famous for botanical gardens, Ooty Lake, and Nilgiri Mountain Railway. Offers scenic beauty, pleasant weather, and colonial charm.",
    location: {
      city: "Ooty (Udhagamandalam)",
      state: "Tamil Nadu",
      country: "India",
      coordinates: { lat: 11.4102, lng: 76.695 },
      address: "Ooty, Tamil Nadu, India",
    },
    rating: 4.5,
    reviews: 75000,
    entryFee: "Gardens ₹30, Boat ride ₹250",
    timings: "Gardens 7 AM - 6:30 PM",
    bestTimeToVisit: "October to June",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    highlights: [
      "Botanical Gardens",
      "Ooty Lake",
      "Doddabetta Peak",
      "Nilgiri Mountain Railway",
      "Rose Garden",
      "Tea Museum",
    ],
    activities: [
      "Boating",
      "Toy train ride",
      "Trekking",
      "Garden walks",
      "Horse riding",
      "Chocolate shopping",
    ],
    nearbyAttractions: [
      { name: "Doddabetta Peak", distance: "9 km" },
      { name: "Ooty Lake", distance: "2 km" },
      { name: "Botanical Gardens", distance: "3 km" },
      { name: "Rose Garden", distance: "2 km" },
      { name: "Pykara Lake", distance: "20 km" },
      { name: "Emerald Lake", distance: "20 km" },
      { name: "Avalanche Lake", distance: "22 km" },
      { name: "Tea Museum", distance: "4 km" },
      { name: "St. Stephen's Church", distance: "2 km" },
      { name: "Mudumalai National Park", distance: "40 km" },
    ],
    howToReach: "Coimbatore Airport 88 km, Mettupalayam Station 40 km, Bangalore 270 km",
    tips: [
      "Book toy train months ahead",
      "Buy homemade chocolates",
      "Carry warm clothes",
      "Avoid weekends for crowd",
    ],
    contactNumber: "+91-423-2441027",
    website: "https://www.tamilnadutourism.org",
    trending: true,
    trendingRank: 21,
    popularity: 88,
  },

  {
    name: "Jaisalmer - Golden City",
    category: "Historical",
    description:
      "Desert city famous for its yellow sandstone architecture and the living Jaisalmer Fort. Offers camel safaris, desert camping, and rich Rajasthani culture.",
    location: {
      city: "Jaisalmer",
      state: "Rajasthan",
      country: "India",
      coordinates: { lat: 26.9157, lng: 70.9083 },
      address: "Jaisalmer, Rajasthan, India",
    },
    rating: 4.7,
    reviews: 62000,
    entryFee: "Fort free, Havelis ₹50-200",
    timings: "Fort 24/7, Havelis 9 AM - 6 PM",
    bestTimeToVisit: "October to March",
    image: "https://images.unsplash.com/photo-1588416936097-41850ab3d86d?w=800",
    highlights: [
      "Jaisalmer Fort",
      "Sam Sand Dunes",
      "Patwon Ki Haveli",
      "Gadisar Lake",
      "Jain Temples",
      "Desert National Park",
    ],
    activities: [
      "Camel safari",
      "Desert camping",
      "Dune bashing",
      "Fort walk",
      "Cultural evening",
      "Stargazing",
    ],
    nearbyAttractions: [
      { name: "Sam Sand Dunes", distance: "40 km" },
      { name: "Patwon Ki Haveli", distance: "1 km" },
      { name: "Gadisar Lake", distance: "2 km" },
      { name: "Bada Bagh", distance: "6 km" },
      { name: "Kuldhara Village", distance: "18 km" },
      { name: "Tanot Mata Temple", distance: "120 km" },
      { name: "Longewala War Memorial", distance: "125 km" },
      { name: "Desert National Park", distance: "40 km" },
      { name: "Jain Temples", distance: "0.5 km" },
      { name: "Nathmal Ki Haveli", distance: "0.5 km" },
    ],
    howToReach: "Jaisalmer Airport, Jaisalmer Station, Jodhpur 285 km",
    tips: [
      "Stay inside the fort",
      "Experience desert camp",
      "Try Dal Baati Churma",
      "Visit haunted Kuldhara",
    ],
    contactNumber: "+91-2992-252406",
    website: "https://tourism.rajasthan.gov.in",
    trending: true,
    trendingRank: 22,
    popularity: 85,
  },

  {
    name: "Mahabalipuram",
    category: "Historical",
    description:
      "UNESCO World Heritage Site famous for rock-cut temples and shore temples. Ancient port city of Pallava dynasty showcasing Dravidian architecture.",
    location: {
      city: "Mahabalipuram",
      state: "Tamil Nadu",
      country: "India",
      coordinates: { lat: 12.6208, lng: 80.1945 },
      address: "Mahabalipuram, Tamil Nadu, India",
    },
    rating: 4.6,
    reviews: 55000,
    entryFee: "₹40 Indians, ₹600 Foreigners",
    timings: "6 AM - 6 PM",
    bestTimeToVisit: "October to March",
    image: "https://images.unsplash.com/photo-1621836860086-4c4f027878b6?w=800",
    highlights: [
      "Shore Temple",
      "Pancha Rathas",
      "Arjuna's Penance",
      "Krishna's Butterball",
      "Mahabalipuram Beach",
      "Seashell Museum",
    ],
    activities: [
      "Temple exploration",
      "Beach walk",
      "Surfing",
      "Stone carving workshops",
      "Cycling",
    ],
    nearbyAttractions: [
      { name: "Shore Temple", distance: "1 km" },
      { name: "Pancha Rathas", distance: "1.5 km" },
      { name: "Arjuna's Penance", distance: "0.5 km" },
      { name: "Krishna's Butterball", distance: "0.5 km" },
      { name: "Crocodile Bank", distance: "14 km" },
      { name: "DakshinaChitra", distance: "25 km" },
      { name: "Tiger Cave", distance: "5 km" },
      { name: "India Seashell Museum", distance: "1.5 km" },
      { name: "Mahabalipuram Beach", distance: "1 km" },
      { name: "Muttukadu Boat House", distance: "20 km" },
    ],
    howToReach: "Chennai Airport 55 km, Chengalpattu Station 30 km, Chennai 60 km",
    tips: [
      "Visit early morning for sunrise",
      "Hire guide for stories",
      "Wear hat/sunscreen",
      "Buy stone artifacts",
    ],
    contactNumber: "+91-44-27442232",
    website: "https://www.tamilnadutourism.org",
    trending: true,
    trendingRank: 23,
    popularity: 80,
  },

  {
    name: "Gangtok",
    category: "Hill Station",
    description:
      "Capital of Sikkim, known for its cleanliness, stunning Kanchenjunga views, and Buddhist monasteries. Gateway to North Sikkim's high-altitude lakes.",
    location: {
      city: "Gangtok",
      state: "Sikkim",
      country: "India",
      coordinates: { lat: 27.3314, lng: 88.6138 },
      address: "Gangtok, Sikkim, India",
    },
    rating: 4.7,
    reviews: 60000,
    entryFee: "Nathula Pass permit ₹200, Monasteries free",
    timings: "Monasteries 8 AM - 5 PM",
    bestTimeToVisit: "March to May, October to December",
    image: "https://images.unsplash.com/photo-1588416936097-41850ab3d86d?w=800",
    highlights: [
      "MG Marg",
      "Rumtek Monastery",
      "Tsomgo Lake",
      "Nathula Pass",
      "Ban Jhakri Falls",
      "Ganesh Tok",
    ],
    activities: [
      "Cable car ride",
      "Yak ride at Tsomgo",
      "Monastery visits",
      "Shopping on MG Marg",
      "Paragliding",
    ],
    nearbyAttractions: [
      { name: "Tsomgo Lake", distance: "40 km" },
      { name: "Nathula Pass", distance: "56 km" },
      { name: "Rumtek Monastery", distance: "24 km" },
      { name: "Baba Mandir", distance: "52 km" },
      { name: "Ban Jhakri Falls", distance: "7 km" },
      { name: "Enchey Monastery", distance: "3 km" },
      { name: "Ganesh Tok", distance: "6 km" },
      { name: "Tashi View Point", distance: "8 km" },
      { name: "Hanuman Tok", distance: "11 km" },
      { name: "Flower Exhibition Centre", distance: "2 km" },
    ],
    howToReach: "Pakyong Airport 30 km, Bagdogra Airport 125 km, New Jalpaiguri Station 120 km",
    tips: [
      "Get permits for Nathula/North Sikkim",
      "No plastic bottles allowed",
      "Respect local culture",
      "Carry warm clothes",
    ],
    contactNumber: "+91-3592-202634",
    website: "https://www.sikkimtourism.gov.in",
    trending: true,
    trendingRank: 24,
    popularity: 84,
  },

  {
    name: "Pondicherry (Puducherry)",
    category: "Beach",
    description:
      "Former French colony with distinct French Quarter, promenade, and spiritual Auroville. Famous for colonial architecture, beaches, and cafes.",
    location: {
      city: "Pondicherry",
      state: "Puducherry",
      country: "India",
      coordinates: { lat: 11.9139, lng: 79.8145 },
      address: "Pondicherry, India",
    },
    rating: 4.6,
    reviews: 88000,
    entryFee: "Auroville free, Museum ₹10",
    timings: "Promenade 24/7, Ashram 8 AM - 12 PM, 2-6 PM",
    bestTimeToVisit: "October to March",
    image: "https://images.unsplash.com/photo-1582555610519-56608825a33f?w=800",
    highlights: [
      "Promenade Beach",
      "Auroville",
      "Sri Aurobindo Ashram",
      "French Quarter (White Town)",
      "Paradise Beach",
      "Manakula Vinayagar Temple",
    ],
    activities: [
      "Cycling in White Town",
      "Meditation at Matrimandir",
      "Scuba diving",
      "Cafe hopping",
      "Heritage walks",
    ],
    nearbyAttractions: [
      { name: "Auroville", distance: "12 km" },
      { name: "Paradise Beach", distance: "8 km" },
      { name: "Serenity Beach", distance: "5 km" },
      { name: "Aurobindo Ashram", distance: "1 km" },
      { name: "Promenade Beach", distance: "0 km" },
      { name: "Manakula Vinayagar Temple", distance: "1 km" },
      { name: "Basilica of the Sacred Heart", distance: "2 km" },
      { name: "Botanical Garden", distance: "3 km" },
      { name: "Chunnambar Boat House", distance: "7 km" },
      { name: "Ousteri Lake", distance: "10 km" },
    ],
    howToReach: "Chennai Airport 135 km, Pondicherry Station, ECR drive from Chennai",
    tips: [
      "Rent a cycle/scooter",
      "Book Matrimandir viewing advance",
      "Try French bakeries",
      "Sunrise at Promenade",
    ],
    contactNumber: "+91-413-2339497",
    website: "https://www.pondytourism.in",
    trending: true,
    trendingRank: 25,
    popularity: 89,
  },

  {
    name: "Kodaikanal - Princess of Hills",
    category: "Hill Station",
    description:
      "Charming hill station in Tamil Nadu centered around a star-shaped lake. Known for misty cliffs, waterfalls, and homemade chocolates.",
    location: {
      city: "Kodaikanal",
      state: "Tamil Nadu",
      country: "India",
      coordinates: { lat: 10.2381, lng: 77.4892 },
      address: "Kodaikanal, Tamil Nadu, India",
    },
    rating: 4.5,
    reviews: 64000,
    entryFee: "Lake boat ₹150, Park ₹30",
    timings: "Lake 9 AM - 5:30 PM",
    bestTimeToVisit: "October to March",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    highlights: [
      "Kodai Lake",
      "Coaker's Walk",
      "Bryant Park",
      "Pillar Rocks",
      "Silver Cascade Falls",
      "Green Valley View",
    ],
    activities: ["Boating", "Cycling around lake", "Trekking", "Horse riding", "Picnic"],
    nearbyAttractions: [
      { name: "Pillar Rocks", distance: "7 km" },
      { name: "Coaker's Walk", distance: "1 km" },
      { name: "Bryant Park", distance: "1 km" },
      { name: "Silver Cascade Falls", distance: "8 km" },
      { name: "Green Valley View", distance: "5.5 km" },
      { name: "Dolphin's Nose", distance: "8 km" },
      { name: "Bear Shola Falls", distance: "3 km" },
      { name: "Guna Caves", distance: "8.5 km" },
      { name: "Moir Point", distance: "10 km" },
      { name: "Berijam Lake", distance: "21 km" },
    ],
    howToReach: "Madurai Airport 120 km, Kodai Road Station 80 km, Bangalore 460 km",
    tips: [
      "Carry umbrella/raincoat",
      "Buy eucalyptus oil",
      "Try homemade cheese",
      "Watch out for monkeys",
    ],
    contactNumber: "+91-4542-241675",
    website: "https://www.tamilnadutourism.org",
    trending: true,
    trendingRank: 26,
    popularity: 83,
  },

  {
    name: "Nainital - Lake District",
    category: "Hill Station",
    description:
      "Popular hill station in Uttarakhand built around the mango-shaped Naini Lake. Famous for boating, viewpoints, and colonial heritage.",
    location: {
      city: "Nainital",
      state: "Uttarakhand",
      country: "India",
      coordinates: { lat: 29.3803, lng: 79.4637 },
      address: "Nainital, Uttarakhand, India",
    },
    rating: 4.5,
    reviews: 69000,
    entryFee: "Zoo ₹50, Boat ride ₹210",
    timings: "Zoo 10 AM - 4:30 PM (Closed Mon)",
    bestTimeToVisit: "March to June, October to February (Snow)",
    image: "https://images.unsplash.com/photo-1566837945700-30057527ade0?w=800",
    highlights: [
      "Naini Lake",
      "Naina Devi Temple",
      "Snow View Point",
      "Eco Cave Gardens",
      "Tiffin Top",
      "Mall Road",
    ],
    activities: ["Boating", "Cable car ride", "Shopping on Mall Road", "Trekking", "Zoo visit"],
    nearbyAttractions: [
      { name: "Naina Devi Temple", distance: "1 km" },
      { name: "Snow View Point", distance: "3 km" },
      { name: "Tiffin Top", distance: "4 km" },
      { name: "Eco Cave Gardens", distance: "2 km" },
      { name: "High Altitude Zoo", distance: "2 km" },
      { name: "Bhimtal", distance: "22 km" },
      { name: "Sattal", distance: "23 km" },
      { name: "Naukuchiatal", distance: "26 km" },
      { name: "Kainchi Dham", distance: "17 km" },
      { name: "Mukteshwar", distance: "50 km" },
    ],
    howToReach: "Pantnagar Airport 65 km, Kathgodam Station 35 km, Delhi 300 km",
    tips: [
      "Walk on Mall Road evening",
      "Visit nearby lakes",
      "Carry light woolens",
      "Try Bal Mithai",
    ],
    contactNumber: "+91-5942-231173",
    website: "https://uttarakhandtourism.gov.in",
    trending: true,
    trendingRank: 27,
    popularity: 86,
  },

  {
    name: "Gir National Park",
    category: "Wildlife",
    description:
      "The only natural habitat of Asiatic Lions in the world. Dry deciduous forest offering thrilling jeep safaris and rich wildlife spotting.",
    location: {
      city: "Sasan Gir",
      state: "Gujarat",
      country: "India",
      coordinates: { lat: 21.1243, lng: 70.8242 },
      address: "Gir, Gujarat, India",
    },
    rating: 4.7,
    reviews: 42000,
    entryFee: "Permit ₹800-1000, Jeep extra",
    timings: "6 AM - 9 AM, 9 AM - 12 PM, 3 PM - 6 PM",
    bestTimeToVisit: "December to March",
    image: "https://images.unsplash.com/photo-1564760055775-d63b17a55c44?w=800",
    highlights: [
      "Asiatic Lions",
      "Devalia Safari Park",
      "Kamleshwar Dam",
      "Crocodile breeding center",
      "Maldhari tribes",
    ],
    activities: ["Jeep safari", "Bird watching", "Nature photography", "Tribal village visit"],
    nearbyAttractions: [
      { name: "Devalia Safari Park", distance: "12 km" },
      { name: "Somnath Temple", distance: "45 km" },
      { name: "Kamleshwar Dam", distance: "10 km" },
      { name: "Jamjir Waterfall", distance: "20 km" },
      { name: "Kankai Mata Temple", distance: "25 km" },
      { name: "Uparkot Fort", distance: "75 km" },
      { name: "Mahabat Maqbara", distance: "75 km" },
      { name: "Diu", distance: "65 km" },
      { name: "Tulsi Shyam", distance: "30 km" },
      { name: "Chorwad Beach", distance: "60 km" },
    ],
    howToReach: "Diu Airport 65 km, Rajkot Airport 160 km, Junagadh Station 60 km",
    tips: [
      "Book safari 3 months advance",
      "Morning safari best for lions",
      "Wear camouflage colors",
      "Closed mid-June to mid-Oct",
    ],
    contactNumber: "+91-2877-285540",
    website: "https://gujarattourism.com",
    trending: true,
    trendingRank: 28,
    popularity: 81,
  },

  {
    name: "Sundarbans National Park",
    category: "Wildlife",
    description:
      "World's largest mangrove forest and UNESCO World Heritage Site. Home to Royal Bengal Tigers, saltwater crocodiles, and unique tidal ecosystem.",
    location: {
      city: "Gosaba",
      state: "West Bengal",
      country: "India",
      coordinates: { lat: 21.9497, lng: 88.8995 },
      address: "Sundarbans, West Bengal, India",
    },
    rating: 4.6,
    reviews: 35000,
    entryFee: "Boat permit ₹600-2000",
    timings: "7 AM - 5 PM",
    bestTimeToVisit: "September to March",
    image: "https://images.unsplash.com/photo-1564760055775-d63b17a55c44?w=800",
    highlights: [
      "Royal Bengal Tiger",
      "Mangrove forests",
      "Sajnekhali Watch Tower",
      "Sudhanyakhali Watch Tower",
      "Dobanki Canopy Walk",
    ],
    activities: ["Boat safari", "Canopy walk", "Bird watching", "Village tour", "Photography"],
    nearbyAttractions: [
      { name: "Sajnekhali Bird Sanctuary", distance: "0 km" },
      { name: "Sudhanyakhali Watch Tower", distance: "10 km" },
      { name: "Dobanki Watch Tower", distance: "20 km" },
      { name: "Netidhopani", distance: "25 km" },
      { name: "Burirdabri", distance: "40 km" },
      { name: "Kanak", distance: "15 km" },
      { name: "Holiday Island", distance: "30 km" },
      { name: "Bhagabatpur Crocodile Project", distance: "50 km" },
      { name: "Piyali Island", distance: "70 km" },
      { name: "Bakkhali", distance: "100 km" },
    ],
    howToReach: "Kolkata Airport 110 km, Canning Station 48 km, then ferry",
    tips: [
      "Stay on boat or eco-resort",
      "Carry mosquito repellent",
      "Binoculars essential",
      "Respect silence",
    ],
    contactNumber: "+91-3218-225211",
    website: "https://wbtourism.gov.in",
    trending: true,
    trendingRank: 29,
    popularity: 80,
  },

  {
    name: "Rann of Kutch",
    category: "Natural Wonder",
    description:
      "World's largest salt desert, famous for the Rann Utsav, white salt plains under moonlight, and Kutchi culture/crafts.",
    location: {
      city: "Dhordo",
      state: "Gujarat",
      country: "India",
      coordinates: { lat: 23.8368, lng: 69.516 },
      address: "Kutch, Gujarat, India",
    },
    rating: 4.7,
    reviews: 58000,
    entryFee: "Permit ₹100, Car ₹50",
    timings: "Sunrise to Sunset (White Rann)",
    bestTimeToVisit: "November to February (Rann Utsav)",
    image: "https://images.unsplash.com/photo-1588416936097-41850ab3d86d?w=800",
    highlights: [
      "White Desert",
      "Rann Utsav",
      "Kala Dungar",
      "Kutch Fossil Park",
      "Handicraft villages",
      "Full moon nights",
    ],
    activities: [
      "Camel cart ride",
      "Paramotoring",
      "Cultural performances",
      "Shopping for handicrafts",
      "Star gazing",
    ],
    nearbyAttractions: [
      { name: "Kala Dungar", distance: "45 km" },
      { name: "India Bridge", distance: "20 km" },
      { name: "Hodka Village", distance: "15 km" },
      { name: "Nirona Village", distance: "40 km" },
      { name: "Bhuj", distance: "80 km" },
      { name: "Mandvi Beach", distance: "140 km" },
      { name: "Dholavira", distance: "200 km" },
      { name: "Aina Mahal", distance: "80 km" },
      { name: "Prag Mahal", distance: "80 km" },
      { name: "Kutch Desert Wildlife Sanctuary", distance: "50 km" },
    ],
    howToReach: "Bhuj Airport/Station 80 km, then taxi to Dhordo",
    tips: [
      "Book Rann Utsav tents early",
      "Visit during full moon",
      "Get permit online or at checkpost",
      "Buy Rogan art",
    ],
    contactNumber: "+91-79-23977200",
    website: "https://www.rannutsav.net",
    trending: true,
    trendingRank: 30,
    popularity: 87,
  },
];

module.exports = top30TrendingDestinations;
